/**
 * Examen final de l'Académie Croupier : 100 questions (QCM) couvrant les 9 modules.
 * `m` = numéro du module d'où vient la question (pour la correction).
 */
export type ExamQuestion = { q: string; choices: string[]; answer: number; m: number };

export const EXAM: ExamQuestion[] = [
  // Module 1 -Introduction au métier
  { m: 1, q: "Au poker, quel est le statut du croupier ?", choices: ["Il joue contre les clients", "Il ne joue jamais, les joueurs s'affrontent entre eux", "Il mise pour le compte de la maison"], answer: 1 },
  { m: 1, q: "Le rôle principal du croupier de poker est de :", choices: ["Gagner le plus de pots possible", "Assurer le bon déroulement de la partie", "Conseiller les joueurs sur leurs mises"], answer: 1 },
  { m: 1, q: "Laquelle n'est PAS une qualité attendue d'un croupier ?", choices: ["La dextérité manuelle", "L'intégrité", "Prendre parti dans les litiges"], answer: 2 },
  { m: 1, q: "Le superviseur de salle qui tranche les litiges est :", choices: ["Le dealer", "Le floor (floorman)", "Le chip runner"], answer: 1 },
  { m: 1, q: "Qui apporte les caves de jetons aux joueurs ?", choices: ["Le chip runner", "Le senior dealer", "Le tournament director"], answer: 0 },
  { m: 1, q: "Le responsable de l'organisation et des décisions d'un tournoi est :", choices: ["Le floor", "Le tournament director (TD)", "Le poker manager"], answer: 1 },
  { m: 1, q: "Un parcours de carrière typique démarre comme :", choices: ["Floor", "Dealer", "Poker manager"], answer: 1 },
  { m: 1, q: "Pour enchaîner les festivals internationaux, quel atout est majeur ?", choices: ["La force physique", "La maîtrise de l'anglais", "Une licence de jeu"], answer: 1 },
  { m: 1, q: "Dans ce métier, l'honnêteté est :", choices: ["Souhaitable", "Non négociable", "Secondaire"], answer: 1 },
  { m: 1, q: "Le senior dealer est généralement affecté :", choices: ["Aux tables de débutants", "Aux tables à fort enjeu et aux finales", "À la caisse"], answer: 1 },
  { m: 1, q: "Le croupier est le premier rempart contre :", choices: ["Les pourboires", "Les erreurs et la triche", "La lenteur du jeu"], answer: 1 },

  // Module 2 -Manipulation des jetons
  { m: 2, q: "Dans la convention courante, le jeton blanc vaut :", choices: ["1", "5", "25"], answer: 0 },
  { m: 2, q: "Le jeton rouge vaut :", choices: ["5", "10", "25"], answer: 0 },
  { m: 2, q: "Le jeton vert vaut :", choices: ["20", "25", "50"], answer: 1 },
  { m: 2, q: "Le jeton noir vaut :", choices: ["50", "100", "500"], answer: 1 },
  { m: 2, q: "Le jeton violet vaut généralement :", choices: ["250", "500", "1000"], answer: 1 },
  { m: 2, q: "Le « chip cutting » consiste à :", choices: ["Laver les cartes", "Séparer une pile en paquets vérifiables d'un regard", "Mélanger les jetons entre eux"], answer: 1 },
  { m: 2, q: "On compte traditionnellement les jetons par :", choices: ["3 et 9", "5 et 20", "4 et 8"], answer: 1 },
  { m: 2, q: "Faire la monnaie doit se faire :", choices: ["Dans les mains, au-dessus du rack", "Sur la table, à la vue de tous", "Le plus discrètement possible"], answer: 1 },
  { m: 2, q: "Le rack (float) se range :", choices: ["En vrac", "Par dénomination, du plus petit au plus grand", "Par couleur, au hasard"], answer: 1 },
  { m: 2, q: "On pousse le pot au gagnant :", choices: ["Dès la river", "Une fois la main formellement terminée", "Avant l'abattage"], answer: 1 },
  { m: 2, q: "Avant de prendre une table, le croupier vérifie toujours :", choices: ["Le nombre de joueurs", "Le code couleur affiché de la salle", "L'état des cartes"], answer: 1 },

  // Module 3 -Manipulation des cartes
  { m: 3, q: "Le mélange à plat qui randomise réellement un jeu neuf est :", choices: ["Le riffle", "Le wash (scramble)", "Le strip"], answer: 1 },
  { m: 3, q: "Le « strip » (box) sert à :", choices: ["Entrelacer les deux paquets", "Casser les séquences en prélevant de petits paquets", "Couper le jeu en deux"], answer: 1 },
  { m: 3, q: "La séquence type d'un croupier est :", choices: ["Wash seul", "Riffle, riffle, strip, riffle", "Strip, strip, riffle"], answer: 1 },
  { m: 3, q: "La « cut card » (carte de coupe) sert à :", choices: ["Compter les cartes", "Masquer la carte du dessous du jeu", "Désigner le donneur"], answer: 1 },
  { m: 3, q: "La distribution (pitch) commence toujours par :", choices: ["Le bouton", "Le joueur à gauche du bouton (small blind)", "La big blind"], answer: 1 },
  { m: 3, q: "Pendant la distribution, la main qui tient le jeu reste :", choices: ["Haute et ouverte", "Basse et fermée", "Au-dessus du rack"], answer: 1 },
  { m: 3, q: "Que ne doit jamais toucher un joueur ?", choices: ["Ses propres cartes", "Le talon (le paquet non distribué)", "Ses jetons"], answer: 1 },
  { m: 3, q: "Entre la vitesse et la régularité/discrétion, le croupier privilégie :", choices: ["La vitesse", "La régularité et la discrétion", "Le spectacle"], answer: 1 },
  { m: 3, q: "Le wash se fait :", choices: ["À chaque main", "À l'ouverture d'une partie et quand le jeu doit être totalement rebrassé", "Jamais"], answer: 1 },
  { m: 3, q: "La coupe du jeu se fait :", choices: ["Après la distribution", "Avant de distribuer", "Pendant le flop"], answer: 1 },
  { m: 3, q: "Pour protéger le jeu, le croupier garde le deck :", choices: ["Haut et visible", "Bas et couvert", "Dans le rack"], answer: 1 },

  // Module 4 -Dealer au Texas Hold'em
  { m: 4, q: "Avant de distribuer, le croupier vérifie que :", choices: ["Les antes sont payées", "La small blind et la big blind sont postées", "Le rake est prélevé"], answer: 1 },
  { m: 4, q: "Le tour de parole préflop commence par :", choices: ["La small blind", "Le joueur à gauche de la big blind", "Le bouton"], answer: 1 },
  { m: 4, q: "Une mise effectuée en plusieurs gestes, interdite, s'appelle :", choices: ["Un string bet", "Un check-raise", "Un cap"], answer: 0 },
  { m: 4, q: "« Burn and turn » signifie :", choices: ["Brûler une carte puis dévoiler la suivante", "Retourner le pot", "Rebrasser le jeu"], answer: 0 },
  { m: 4, q: "Combien de cartes brûle-t-on avant le flop ?", choices: ["Zéro", "Une", "Trois"], answer: 1 },
  { m: 4, q: "Le flop dévoile :", choices: ["1 carte", "3 cartes", "5 cartes"], answer: 1 },
  { m: 4, q: "Un side pot se crée quand :", choices: ["Un joueur relance", "Un joueur fait tapis pour moins que les autres", "Il y a égalité"], answer: 1 },
  { m: 4, q: "Le pot principal est plafonné :", choices: ["Au pot total", "Au tapis du joueur all-in multiplié par le nombre de suiveurs", "Au double de la mise"], answer: 1 },
  { m: 4, q: "Le joueur à tapis pour le pot principal peut-il gagner le side pot ?", choices: ["Oui", "Non", "Seulement en cas d'égalité"], answer: 1 },
  { m: 4, q: "Si la river a donné lieu à une mise, qui montre en premier au showdown ?", choices: ["Le bouton", "Le dernier à avoir misé ou relancé", "La big blind"], answer: 1 },
  { m: 4, q: "Après un check général à la river, on montre :", choices: ["Personne", "Dans le sens horaire à partir du bouton", "Le plus gros tapis d'abord"], answer: 1 },
  { m: 4, q: "En cas d'égalité parfaite entre deux mains, le croupier :", choices: ["Rejoue la main", "Partage le pot (split)", "Donne au plus proche du bouton"], answer: 1 },

  // Module 5 -Situations en cash game
  { m: 5, q: "Un joueur absent à son tour de parole voit sa main :", choices: ["Conservée", "Jetée (mucked)", "Jouée automatiquement"], answer: 1 },
  { m: 5, q: "Tant qu'il occupe son siège, le joueur absent doit :", choices: ["Rien", "Payer les blindes quand elles passent (sauf sit out)", "Quitter la table"], answer: 1 },
  { m: 5, q: "Un joueur qui a raté sa big blind peut revenir :", choices: ["Gratuitement", "En postant la big blind manquée ou en attendant le bouton", "Jamais"], answer: 1 },
  { m: 5, q: "Un nouvel arrivant entre en jeu :", choices: ["Gratuitement", "En postant l'équivalent de la big blind ou en attendant la blinde", "En payant le rake"], answer: 1 },
  { m: 5, q: "La cave minimum d'une table s'exprime :", choices: ["En euros uniquement", "En big blinds ou en montant", "En nombre de jetons"], answer: 1 },
  { m: 5, q: "Un joueur peut recaver :", choices: ["Au milieu d'une main", "Entre les mains", "Jamais"], answer: 1 },
  { m: 5, q: "Le « rat-holing » consiste à :", choices: ["Cacher ses cartes", "Retirer discrètement des jetons de la table en cours de session", "Bluffer au tapis"], answer: 1 },
  { m: 5, q: "Le rat-holing est :", choices: ["Autorisé", "Interdit", "Toléré la nuit"], answer: 1 },
  { m: 5, q: "Ce qu'on pose sur la table doit y rester jusqu'à :", choices: ["La fin de la main", "Ce qu'on quitte définitivement le siège", "Le prochain bouton"], answer: 1 },
  { m: 5, q: "Le « sit out » permet au joueur :", choices: ["De continuer à payer les blindes", "De ne pas payer les blindes pendant son absence", "D'être éliminé"], answer: 1 },
  { m: 5, q: "Les places libres et les arrivées sont signalées :", choices: ["Aux joueurs", "Au floor", "À personne"], answer: 1 },

  // Module 6 -Situations en tournoi
  { m: 6, q: "En tournoi, les tables doivent rester :", choices: ["À 9 joueurs", "Équilibrées en nombre de joueurs", "Aléatoires"], answer: 1 },
  { m: 6, q: "Pour équilibrer, on déplace généralement le joueur qui :", choices: ["A le plus gros tapis", "Serait le prochain à payer la big blind", "Vient d'arriver"], answer: 1 },
  { m: 6, q: "Lors d'un cassage de table, chaque joueur :", choices: ["Garde sa place", "Tire un nouveau siège (redraw)", "Est éliminé"], answer: 1 },
  { m: 6, q: "Le chip race sert à :", choices: ["Accélérer les blindes", "Retirer une dénomination de jetons devenue inutile", "Prélever le rake"], answer: 1 },
  { m: 6, q: "Pour les restes d'un chip race, on départage :", choices: ["Au hasard", "En tirant des cartes (la plus haute gagne le jeton)", "Au tapis"], answer: 1 },
  { m: 6, q: "À chaque niveau de tournoi :", choices: ["Les blindes baissent", "Les blindes (et parfois les antes) augmentent", "Rien ne change"], answer: 1 },
  { m: 6, q: "Le croupier annonce le nouveau niveau :", choices: ["À la fin du niveau", "Dès qu'il démarre", "Jamais"], answer: 1 },
  { m: 6, q: "Le tournoi suit :", choices: ["Le rythme des joueurs", "Une horloge", "Le floor"], answer: 1 },
  { m: 6, q: "La « règle du temps » (clock) s'applique quand :", choices: ["Un joueur tarde trop à décider", "Le niveau change", "Un side pot existe"], answer: 0 },
  { m: 6, q: "Le chip race se déroule :", choices: ["En coulisses", "À la vue de tous", "Par le floor seul"], answer: 1 },
  { m: 6, q: "Un déséquilibre de tables est signalé :", choices: ["Par les joueurs", "Par le croupier au floor", "Par personne"], answer: 1 },

  // Module 7 -Gestion des erreurs et litiges
  { m: 7, q: "Un misdeal est :", choices: ["Une donne irrégulière qui annule la main", "Un très gros pot", "Un bluff raté"], answer: 0 },
  { m: 7, q: "Un misdeal ne peut plus être déclaré une fois que :", choices: ["Le flop est sorti", "Une action significative a eu lieu", "Le rake est prélevé"], answer: 1 },
  { m: 7, q: "Une carte exposée par la faute d'un joueur :", choices: ["Est remplacée", "Reste généralement la sienne", "Annule la main"], answer: 1 },
  { m: 7, q: "Face à une mise contestée, tant que rien n'est tranché :", choices: ["On continue normalement", "On ne touche plus au pot", "On rembourse le joueur"], answer: 1 },
  { m: 7, q: "Face à un litige entre joueurs, la règle d'or est :", choices: ["Donner raison au plus ancien", "La neutralité absolue", "Rejouer la main"], answer: 1 },
  { m: 7, q: "Qui tranche un litige ?", choices: ["Le croupier", "Le floor", "Les joueurs"], answer: 1 },
  { m: 7, q: "Le rôle du croupier dans un litige est de :", choices: ["Juger", "Décrire les faits", "Choisir un camp"], answer: 1 },
  { m: 7, q: "La première carte donnée au mauvais joueur est :", choices: ["Sans conséquence", "Un cas de misdeal", "La faute du joueur"], answer: 1 },
  { m: 7, q: "Une action hors-tour (avant son tour) peut être :", choices: ["Toujours valable", "Contraignante ou annulée selon ce qui s'est passé", "Toujours ignorée"], answer: 1 },
  { m: 7, q: "Une mise irrégulière (montant insuffisant) doit être :", choices: ["Acceptée telle quelle", "Corrigée immédiatement", "Rejouée au tour suivant"], answer: 1 },
  { m: 7, q: "Au moindre doute sur un misdeal, le croupier :", choices: ["Décide seul", "Appelle le floor", "Rembourse tout le monde"], answer: 1 },

  // Module 8 -Le prélèvement du rake
  { m: 8, q: "Le rake est :", choices: ["Un pourboire", "La commission prélevée par la salle en cash game", "Une mise obligatoire"], answer: 1 },
  { m: 8, q: "En tournoi, le rake sur les pots :", choices: ["Existe", "N'existe pas (la salle se rémunère via les droits d'entrée)", "Est doublé"], answer: 1 },
  { m: 8, q: "Le rake est généralement :", choices: ["Un montant fixe", "Un pourcentage du pot avec un plafond (cap)", "Aléatoire"], answer: 1 },
  { m: 8, q: "Le pourcentage de rake tourne souvent autour de :", choices: ["1 %", "5 %", "20 %"], answer: 1 },
  { m: 8, q: "« No flop, no drop » signifie :", choices: ["Pas de rake si la main se termine avant le flop", "Pas de jeu sans flop", "Pas de pot sans mise"], answer: 0 },
  { m: 8, q: "Le rake se prélève :", choices: ["Après avoir poussé le pot", "Sur le pot, devant les joueurs, avant de pousser", "À la caisse en fin de partie"], answer: 1 },
  { m: 8, q: "Le « jackpot drop » est :", choices: ["Le rake lui-même", "Un montant séparé alimentant un jackpot", "Un pourboire pour le croupier"], answer: 1 },
  { m: 8, q: "Le jackpot drop et le rake :", choices: ["Sont identiques", "Vont dans des emplacements séparés", "Sont optionnels"], answer: 1 },
  { m: 8, q: "Un « bad beat jackpot » récompense :", choices: ["Le meilleur joueur", "Une grosse main perdante", "Le croupier"], answer: 1 },
  { m: 8, q: "Sur une main avec side pots, le rake :", choices: ["Se prend deux fois", "Se prélève une seule fois, proprement", "N'est pas prélevé"], answer: 1 },

  // Module 9 -Les annonces du dealer
  { m: 9, q: "Le croupier répète chaque décision pour :", choices: ["Faire le spectacle", "Que tout le monde suive et éviter les malentendus", "Gagner du temps"], answer: 1 },
  { m: 9, q: "« Suit » se dit en anglais :", choices: ["Raise", "Call", "Fold"], answer: 1 },
  { m: 9, q: "« Relance » se dit :", choices: ["Call", "Raise", "Check"], answer: 1 },
  { m: 9, q: "« Tapis » (all-in) se dit :", choices: ["All-in", "Cap", "Pass"], answer: 0 },
  { m: 9, q: "« Se coucher » se dit :", choices: ["Fold", "Stand", "Pass"], answer: 0 },
  { m: 9, q: "« Place libre » se dit :", choices: ["Seat open", "Free chair", "Table open"], answer: 0 },
  { m: 9, q: "« Joueur en jeu » se dit :", choices: ["Player in", "New man", "Seat in"], answer: 0 },
  { m: 9, q: "« Abattage » se dit :", choices: ["Showdown", "Reveal", "Open cards"], answer: 0 },
  { m: 9, q: "« Parole à [siège] » se dit :", choices: ["Action on (player)", "Talk to", "Turn on"], answer: 0 },
  { m: 9, q: "Appeler le floor est :", choices: ["Un aveu de faiblesse", "La bonne procédure", "Interdit"], answer: 1 },
  { m: 9, q: "Quand une place se libère, le croupier annonce :", choices: ["Rien", "« Place libre » (seat open)", "Au manager uniquement"], answer: 1 },
  { m: 9, q: "La clarté des montants annoncés évite :", choices: ["Les pourboires", "Les mises contestées", "La triche"], answer: 1 },

  // --- Banque elargie (questions supplementaires, tirage aleatoire a chaque tentative) ---
  { m: 1, q: "Comment le module qualifie-t-il le croupier de poker à sa table ?", choices: ["Le chef d'orchestre de la table", "Un joueur parmi les autres", "Un simple distributeur de cartes"], answer: 0 },
  { m: 1, q: "À la roulette ou au blackjack, contrairement au poker, le croupier :", choices: ["Ne touche jamais les jetons", "Joue contre les clients", "Désigne lui-même le gagnant"], answer: 1 },
  { m: 1, q: "Parmi ces tâches, laquelle fait partie du rôle du croupier de poker ?", choices: ["Conseiller les joueurs sur leur stratégie", "Miser à la place des joueurs", "Prélever le rake"], answer: 2 },
  { m: 1, q: "Selon le module, un bon croupier rend la table :", choices: ["Fluide, agréable et équitable", "Rapide mais tendue", "Silencieuse et impersonnelle"], answer: 0 },
  { m: 1, q: "La qualité décrite comme « aucune erreur sur le pot, les blindes ou l'ordre d'action » correspond à :", choices: ["Le sang-froid", "La rigueur et la concentration", "Le sens du service"], answer: 1 },
  { m: 1, q: "À quoi sert le calcul mental chez le croupier selon le module ?", choices: ["À deviner les cartes des joueurs", "À tenir les comptes de la caisse en fin de nuit", "À annoncer les mises, faire la monnaie et calculer le rake et les side pots"], answer: 2 },
  { m: 1, q: "Gérer les litiges et les joueurs en tilt avec calme et autorité relève de :", choices: ["L'endurance", "Le sang-froid", "La dextérité manuelle"], answer: 1 },
  { m: 1, q: "Pourquoi l'endurance est-elle citée comme qualité requise ?", choices: ["Pour tenir la concentration sur de longues sessions, souvent de nuit", "Pour soulever les caves de jetons lourdes", "Pour courir entre les tables et la caisse"], answer: 0 },
  { m: 1, q: "Quel poste seconde le floor et gère les listes d'attente et les changements de table ?", choices: ["Le chip runner", "Le senior dealer", "L'assistant floor"], answer: 2 },
  { m: 1, q: "Qui dirige toute la salle de poker (planning, équipe, résultats) ?", choices: ["Le poker manager", "Le tournament director", "Le floor"], answer: 0 },
  { m: 1, q: "Selon le module, quelle est la progression typique après le poste de dealer ?", choices: ["Directement poker manager, puis floor", "Senior dealer, puis floor, puis la direction de salle ou de tournois", "Chip runner, puis caissier, puis senior dealer"], answer: 1 },
  { m: 2, q: "Le jeton jaune ou orange vaut généralement :", choices: ["1000", "500", "100"], answer: 0 },
  { m: 2, q: "Concernant les valeurs des jetons d'une salle à l'autre, le cours indique qu'elles :", choices: ["sont identiques partout dans le monde", "varient d'une salle à l'autre, mais une convention revient souvent", "ne servent qu'aux tournois"], answer: 1 },
  { m: 2, q: "Avec l'habitude, l'œil d'un bon croupier reconnaît une pile de cinq ou de vingt :", choices: ["seulement en recomptant jeton par jeton", "après avoir aligné une pile de référence à chaque fois", "instantanément, sans recompter jeton par jeton"], answer: 2 },
  { m: 2, q: "Selon le module, la compétence reine du métier est :", choices: ["compter vite et juste les jetons", "mélanger les cartes en silence", "annoncer en anglais"], answer: 0 },
  { m: 2, q: "Pour faire la monnaie, faire les opérations dans les mains au-dessus du rack est :", choices: ["recommandé pour aller plus vite", "à proscrire : tout se fait sur la table à la vue de tous", "autorisé uniquement en tournoi"], answer: 1 },
  { m: 2, q: "Faire la monnaie, c'est :", choices: ["échanger une grosse dénomination contre des plus petites, ou l'inverse", "prélever le rake sur le pot", "constituer la cave d'un nouveau joueur"], answer: 0 },
  { m: 2, q: "La transparence lors du change de jetons sert avant tout à :", choices: ["impressionner les joueurs", "accélérer la partie", "éviter tout malentendu et protéger le croupier comme le joueur"], answer: 2 },
  { m: 2, q: "Le plateau de jetons placé devant le croupier s'appelle :", choices: ["le rack (ou float)", "la cave", "le pot"], answer: 0 },
  { m: 2, q: "Un rack propre et organisé permet surtout :", choices: ["de gagner plus de pourboires", "de rendre la monnaie et de prélever le rake sans hésiter", "de jouer plus de mains"], answer: 1 },
  { m: 2, q: "Constituer une cave pour un joueur, c'est assembler un montant précis en jetons utilisables, qui est :", choices: ["compté en silence dans les mains", "remis sans vérification pour aller vite", "vérifié à voix haute avant de le remettre"], answer: 2 },
  { m: 3, q: "Combien de cartes étale-t-on faces cachées sur le tapis pour réaliser le wash ?", choices: ["52 cartes", "32 cartes", "Seulement la moitié du jeu"], answer: 0 },
  { m: 3, q: "Pendant le wash, on brasse les cartes en :", choices: ["Petits gestes secs vers soi", "Larges mouvements circulaires pendant quelques secondes", "Les empilant aussitôt par couleur"], answer: 1 },
  { m: 3, q: "Selon le module, sans wash, les cartes :", choices: ["Deviennent impossibles à distribuer", "Sont automatiquement marquées", "Gardent une trace de leur ordre précédent"], answer: 2 },
  { m: 3, q: "Combien de riffle shuffle enchaîne-t-on généralement après avoir rassemblé les cartes ?", choices: ["Deux", "Cinq", "Un seul"], answer: 0 },
  { m: 3, q: "Pendant le mélange standard, le jeu doit être maintenu :", choices: ["Bien au-dessus du tapis pour le montrer", "Bas sur le tapis pour ne rien exposer", "Dans le rack à jetons"], answer: 1 },
  { m: 3, q: "La séquence type de mélange du croupier doit être :", choices: ["Bruyante pour rythmer la table", "Lente et appuyée", "Fluide et silencieuse"], answer: 2 },
  { m: 3, q: "Lors de la coupe, le jeu est séparé en :", choices: ["Deux paquets francs", "Trois petits tas", "Quatre piles égales"], answer: 0 },
  { m: 3, q: "Qui peut réaliser la coupe du jeu selon la salle ?", choices: ["Uniquement le joueur au bouton", "Le croupier qui la propose ou la réalise lui-même", "Toujours la big blind"], answer: 1 },
  { m: 3, q: "Le « pitch » consiste à envoyer chaque carte :", choices: ["En la lançant en l'air vers le joueur", "Face visible pour gagner du temps", "À plat, une à une, vers le bon joueur"], answer: 2 },
  { m: 3, q: "Dans quel sens tourne la distribution une fois commencée ?", choices: ["Dans le sens horaire", "Dans le sens antihoraire", "En zigzag d'un bout à l'autre de la table"], answer: 0 },
  { m: 3, q: "Une carte qui glisse trop loin ou se retourne pendant la distribution est :", choices: ["Sans conséquence si la main continue", "Une faute à éviter", "Un signe de bonne rapidité"], answer: 1 },
  { m: 4, q: "Qu'est-ce que le bouton indique à chaque main ?", choices: ["La position du donneur, qui tourne d'un siège à chaque main", "Le joueur qui a le plus gros tapis", "Le joueur qui doit prélever le rake"], answer: 0 },
  { m: 4, q: "Combien de cartes fermées chaque joueur reçoit-il au Texas Hold'em ?", choices: ["Une", "Trois", "Deux"], answer: 2 },
  { m: 4, q: "Par quel joueur commence la distribution des cartes fermées ?", choices: ["Le bouton", "La small blind", "La big blind"], answer: 1 },
  { m: 4, q: "Une relance valide doit être :", choices: ["Annoncée ou posée en un seul mouvement", "Toujours posée en deux temps", "Validée par les autres joueurs"], answer: 0 },
  { m: 4, q: "Face à un string bet, le croupier doit :", choices: ["L'accepter tel quel", "L'arrêter", "Demander l'avis du floor à chaque fois"], answer: 1 },
  { m: 4, q: "Quand rassemble-t-on les mises au centre ?", choices: ["Avant chaque mise", "Une fois le tour d'enchères terminé", "Seulement à l'abattage"], answer: 1 },
  { m: 4, q: "« Brûler » une carte signifie :", choices: ["La déchirer", "La donner au joueur suivant", "L'écarter face cachée"], answer: 2 },
  { m: 4, q: "Pourquoi brûle-t-on une carte avant chaque carte commune ?", choices: ["Pour protéger contre les cartes éventuellement marquées et standardiser la procédure", "Pour accélérer la distribution", "Pour augmenter le pot"], answer: 0 },
  { m: 4, q: "Combien de cartes dévoile-t-on au turn puis à la river ?", choices: ["Trois à chaque fois", "Une au turn et une à la river", "Deux au turn et une à la river"], answer: 1 },
  { m: 4, q: "Comment doit rester le pot une fois constitué au centre ?", choices: ["Caché aux joueurs", "Bien empilé par dénomination", "Mélangé en vrac"], answer: 1 },
  { m: 4, q: "Le surplus misé par les autres joueurs au-delà du tapis de l'all-in alimente :", choices: ["Le rake", "Le pot principal", "Le side pot"], answer: 2 },
  { m: 5, q: "Comment le croupier doit-il gérer un joueur qui s'absente un instant de sa place ?", choices: ["Sans drame et sans ralentir la table", "En suspendant la main pour l'attendre", "En appelant systématiquement le floor"], answer: 0 },
  { m: 5, q: "Quel signalement dispense un joueur occupant son siège de devoir les blindes pendant son absence ?", choices: ["Le buy-in", "Le redraw", "Le « sit out »"], answer: 2 },
  { m: 5, q: "Pourquoi un joueur ne peut-il pas sauter son tour de blinde après une absence ?", choices: ["Pour ne pas profiter des bonnes positions", "Pour accélérer la partie", "Pour payer le rake"], answer: 0 },
  { m: 5, q: "Selon le module, de quoi dépend la règle exacte de retour après une miss blind ?", choices: ["Du nombre de joueurs", "De la salle", "Du montant du pot"], answer: 1 },
  { m: 5, q: "Lors d'un changement de siège, le joueur reste soumis :", choices: ["À une nouvelle cave minimum", "À l'autorisation des autres joueurs", "À ses obligations de blinde"], answer: 2 },
  { m: 5, q: "Pourquoi le croupier indique-t-il au floor toute place qui se libère et toute arrivée ?", choices: ["Pour que la liste d'attente soit tenue à jour", "Pour calculer le rake", "Pour relancer une nouvelle main"], answer: 0 },
  { m: 5, q: "Outre une cave minimum, qu'une table possède-t-elle souvent ?", choices: ["Un nombre de joueurs imposé", "Une cave maximum", "Une horloge de niveaux"], answer: 1 },
  { m: 5, q: "Que vérifie le croupier avant de constituer les jetons d'un joueur ?", choices: ["Que le buy-in respecte les limites de cave", "Que le joueur a payé son ante", "Que la table est complète"], answer: 0 },
  { m: 5, q: "À quel moment un joueur ne peut-il jamais recaver ?", choices: ["Entre les mains", "À son arrivée à la table", "Au milieu d'une main en cours"], answer: 2 },
  { m: 5, q: "Quel est le but du rat-holing pour le joueur qui le pratique ?", choices: ["Distribuer plus vite", "Protéger ses gains", "Changer de siège"], answer: 1 },
  { m: 5, q: "Que doit faire le croupier au sujet des jetons en cours de jeu ?", choices: ["Veiller à ce que personne ne fasse disparaître de jetons", "Recompter le pot à chaque main", "Autoriser le retrait discret de jetons"], answer: 0 },
  { m: 6, q: "Quand déplace-t-on un joueur pour rétablir l'équilibre des tables ?", choices: ["Dès qu'une table compte au moins un joueur de plus qu'une autre", "Seulement à la fin de chaque niveau", "Uniquement quand une table est pleine"], answer: 0 },
  { m: 6, q: "Qui organise concrètement le mouvement d'un joueur lors du balancing ?", choices: ["Le croupier lui-même", "Le floor", "Le joueur déplacé"], answer: 1 },
  { m: 6, q: "Lors des éliminations, quelles tables casse-t-on en priorité ?", choices: ["Les tables à fort enjeu", "Les tables les plus récentes", "Les tables les moins peuplées"], answer: 2 },
  { m: 6, q: "Lors d'un cassage de table, le croupier de la table cassée doit notamment veiller à ce que :", choices: ["Les tapis suivent bien leurs propriétaires", "Les blindes soient remboursées", "Le rake soit prélevé une dernière fois"], answer: 0 },
  { m: 6, q: "Pourquoi procède-t-on à un chip race sur une dénomination ?", choices: ["Parce que les joueurs en demandent davantage", "Parce que les petites valeurs ne servent plus aux blindes", "Parce que le floor veut accélérer les éliminations"], answer: 1 },
  { m: 6, q: "Au cours d'un chip race, on échange les petits jetons contre :", choices: ["Des jetons plus gros", "De l'argent réel", "Des antes supplémentaires"], answer: 0 },
  { m: 6, q: "Lors d'un chip race, qui reçoit le jeton arrondi parmi les restes ?", choices: ["Le joueur au plus gros tapis", "Le joueur tirant la carte la plus haute", "Le joueur le plus proche du bouton"], answer: 1 },
  { m: 6, q: "Selon le module, quelle est la conséquence d'une erreur de niveau ?", choices: ["Elle est sans incidence sur la main", "Elle ne touche que la pause suivante", "Elle fausse toute la main"], answer: 2 },
  { m: 6, q: "Lors d'un changement de niveau, en plus d'annoncer le niveau, le croupier doit :", choices: ["Ajuster les mises obligatoires", "Rebrasser entièrement le jeu", "Casser la table"], answer: 0 },
  { m: 6, q: "Concernant le tempo, le croupier doit maintenir :", choices: ["Le tapis le plus élevé possible", "Un rythme régulier de mains par niveau", "Une seule main par joueur"], answer: 1 },
  { m: 6, q: "Les pauses d'un tournoi sont :", choices: ["Décidées par les joueurs à la majorité", "Laissées à la libre appréciation du croupier", "Prévues par la structure"], answer: 2 },
  { m: 7, q: "Que fait le croupier lorsqu'un misdeal est constaté ?", choices: ["On reprend les cartes et on redistribue", "On poursuit la main normalement", "On annule le pot et on passe au joueur suivant"], answer: 0 },
  { m: 7, q: "Lequel de ces cas est un exemple classique de misdeal ?", choices: ["Un joueur se couche trop vite", "Un mauvais nombre de cartes distribuées", "Un joueur conteste son gain"], answer: 1 },
  { m: 7, q: "Selon les règles de la salle, une carte exposée par erreur par le croupier pendant la distribution peut :", choices: ["Être remplacée et devenir la carte brûlée", "Être redonnée au joueur sans changement", "Forcer un nouveau wash complet"], answer: 0 },
  { m: 7, q: "Quand un joueur expose une carte par sa propre faute, il :", choices: ["Peut demander une nouvelle carte", "En assume la conséquence", "Provoque un misdeal automatique"], answer: 1 },
  { m: 7, q: "Pour appliquer la procédure d'une carte exposée, le croupier doit :", choices: ["Improviser selon la situation", "Demander l'avis des joueurs", "Appliquer le règlement sans improviser"], answer: 2 },
  { m: 7, q: "Pour reconstituer la vérité de la table lors d'une mise contestée, le croupier s'appuie sur :", choices: ["Ce qui est visible et les déclarations cohérentes des joueurs", "Son intuition personnelle", "Le montant qui l'arrange le plus"], answer: 0 },
  { m: 7, q: "En dernier recours pour trancher une mise contestée, on peut s'appuyer sur :", choices: ["Le vote des joueurs à la table", "Le floor ou la vidéosurveillance", "Le joueur qui a la plus grosse main"], answer: 1 },
  { m: 7, q: "Face à un litige entre joueurs, l'attitude du croupier doit être :", choices: ["Prendre parti pour le plus calme", "Trancher rapidement lui-même", "Garder son calme et figer la situation"], answer: 2 },
  { m: 7, q: "L'annonce qui appelle le superviseur en cas de litige est :", choices: ["« Floor ! »", "« Misdeal ! »", "« Showdown ! »"], answer: 0 },
  { m: 7, q: "Une mise irrégulière peut correspondre à :", choices: ["Une relance annoncée à voix haute", "Des jetons cachés derrière (montant insuffisant)", "Un tapis complet et visible"], answer: 1 },
  { m: 8, q: "Pourquoi la salle prélève-t-elle un rake en cash game ?", choices: ["Parce qu'elle ne joue pas et doit se rémunérer ainsi", "Pour rembourser les pertes des joueurs", "Pour payer les pourboires du croupier"], answer: 0 },
  { m: 8, q: "Devant qui le croupier prélève-t-il le rake ?", choices: ["En coulisses, à l'abri des regards", "Devant les joueurs, sur le pot", "Uniquement devant le superviseur"], answer: 1 },
  { m: 8, q: "À quel moment précis le croupier prélève-t-il le rake ?", choices: ["Après avoir poussé le pot au gagnant", "Une fois la partie terminée, à la caisse", "Sur le pot, avant de le pousser au gagnant"], answer: 2 },
  { m: 8, q: "Comment la salle se rémunère-t-elle en tournoi, puisqu'il n'y a pas de rake sur les pots ?", choices: ["Via les droits d'entrée", "En doublant les blindes", "En prélevant un pourboire sur chaque pot"], answer: 0 },
  { m: 8, q: "Que désigne le plafond appelé cap dans le calcul du rake ?", choices: ["Le montant minimum à prélever", "Le montant maximum au-delà duquel on ne prélève plus", "Le pourcentage exact appliqué au pot"], answer: 1 },
  { m: 8, q: "Comment le croupier gère-t-il les jetons de rake pendant la main ?", choices: ["Il les met de côté au fur et à mesure dans l'emplacement prévu", "Il les laisse dans le pot jusqu'à la fin", "Il les remet directement dans son tapis"], answer: 0 },
  { m: 8, q: "À partir de quel moment le rake commence-t-il à courir avec la règle no flop no drop ?", choices: ["Dès le premier tour de mises préflop", "À partir du moment où un flop est distribué", "Seulement à la river"], answer: 1 },
  { m: 8, q: "Quel est l'intérêt de la règle no flop no drop ?", choices: ["Augmenter le rake sur les grosses mains", "Accélérer la distribution des cartes", "Éviter de taxer les mains qui ne vont nulle part"], answer: 2 },
  { m: 8, q: "Le jackpot drop correspond le plus souvent à :", choices: ["Un petit montant fixe destiné à alimenter un jackpot", "Un pourcentage variable du pot", "La part du rake reversée au croupier"], answer: 0 },
  { m: 8, q: "Que doit faire le croupier vis-à-vis du rake et du jackpot drop ?", choices: ["Les regrouper dans un même emplacement", "Ne jamais confondre les deux prélèvements", "Prélever le jackpot drop avant le flop seulement"], answer: 1 },
  { m: 8, q: "Sur une main avec side pots, comment le rake est-il prélevé pour ne pas pénaliser le joueur à tapis qui ne dispute que le pot principal ?", choices: ["Deux fois, une par pot", "À parts égales sur chaque side pot", "Une seule fois, proprement, en restant clair sur ce qui sort de chaque pot"], answer: 2 },
  { m: 9, q: "Selon le module, une table où le dealer parle bien est une table qui :", choices: ["ne se dispute pas", "joue plus vite", "donne plus de pourboires"], answer: 0 },
  { m: 9, q: "Annoncer clairement l'action permet d'éviter :", choices: ["les pourboires trop faibles", "les actions hors-tour et les malentendus", "le mélange des cartes"], answer: 1 },
  { m: 9, q: "Quand un joueur relance, le croupier annonce :", choices: ["« suit »", "« tapis »", "« relance à [montant] »"], answer: 2 },
  { m: 9, q: "Pour une mise à tapis, le croupier annonce « tapis » avec :", choices: ["le nom du joueur", "le montant total", "la couleur des jetons"], answer: 1 },
  { m: 9, q: "Pour désigner le joueur qui doit agir, le croupier dit :", choices: ["« parole à [siège] »", "« suit »", "« abattage »"], answer: 0 },
  { m: 9, q: "Quand un joueur arrive à la table, le croupier signale :", choices: ["« place libre » (seat open)", "« joueur en jeu » (player in)", "« abattage » (showdown)"], answer: 1 },
  { m: 9, q: "Selon le module, ces annonces au floor servent notamment à :", choices: ["impressionner les joueurs", "compter le rake", "tenir la liste d'attente à jour et garder les tables pleines"], answer: 2 },
  { m: 9, q: "La taille du pot peut être annoncée si un joueur la demande, à condition que :", choices: ["la salle l'autorise", "le pot dépasse un certain montant", "tous les joueurs soient à tapis"], answer: 0 },
  { m: 9, q: "Pour assurer la clarté des montants, le croupier doit :", choices: ["parler le plus vite possible", "articuler, montrer les jetons et confirmer avant de poursuivre", "laisser les joueurs compter eux-mêmes"], answer: 1 },
  { m: 9, q: "Selon le module, mieux vaut un floor appelé pour rien que :", choices: ["une partie ralentie", "une table mal remplie", "une mauvaise décision prise seul"], answer: 2 },
  { m: 9, q: "En anglais, « abattage » se dit :", choices: ["showdown", "action on", "player in"], answer: 0 },
];
