/**
 * Glossaire poker, dictionnaire des termes, défini simplement avec exemples.
 * Lot de départ (à étendre vers 300+ termes). Trié alphabétiquement à l'affichage.
 */

export type Term = {
  term: string;
  def: string;
  example?: string;
};

export const GLOSSARY: Term[] = [
  { term: "Action", def: "Le fait de miser, relancer ou suivre. Désigne aussi l'animation d'une table : « il y a de l'action »." },
  { term: "Add-on", def: "Achat de jetons supplémentaires proposé une seule fois dans certains tournois, généralement à la fin de la période de recave.", example: "À la pause, tous les joueurs prennent l'add-on de 3000 jetons." },
  { term: "All-in", def: "Miser la totalité de ses jetons. On dit aussi « faire tapis ».", example: "Avec As-Roi, il pousse all-in pour 40 big blinds." },
  { term: "Ante", def: "Petite mise obligatoire payée par tous les joueurs avant la distribution, surtout en tournoi, pour gonfler le pot." },
  { term: "Backdoor", def: "Tirage « par la porte de derrière » qui nécessite d'améliorer au turn ET à la river pour se compléter.", example: "Un backdoor flush : deux cartes de la couleur au flop, il en faut encore deux." },
  { term: "Bad beat", def: "Perdre une main qu'on était très largement favori à gagner, à cause d'une carte improbable.", example: "Son brelan d'As battu par une couleur rentrée à la river : le bad beat classique." },
  { term: "Barrel", def: "Continuer à miser sur plusieurs tours consécutifs, souvent en bluff. « Double barrel » = miser flop et turn." },
  { term: "Bet", def: "Être le premier à miser sur un tour d'enchères." },
  { term: "Big blind", def: "La mise obligatoire pleine, posée à gauche de la small blind. Sert d'unité de mesure des tapis (en BB)." },
  { term: "Blocker", def: "Carte que vous détenez et qui réduit les combinaisons possibles de l'adversaire.", example: "Avoir l'As de pique « bloque » la couleur max adverse." },
  { term: "Bluff", def: "Miser ou relancer avec une main faible pour faire coucher une meilleure main." },
  { term: "Board", def: "Le tableau : l'ensemble des cartes communes posées au centre (flop, turn, river)." },
  { term: "Bounty", def: "Prime mise sur la tête d'un joueur dans un tournoi « knockout » : l'éliminer rapporte un bonus." },
  { term: "Bubble", def: "La place juste avant les places payées. Être « sur la bulle », c'est risquer d'être éliminé sans rien gagner." },
  { term: "Button", def: "Le bouton du donneur. Indique le joueur en dernière position post-flop, la meilleure place à la table." },
  { term: "Buy-in", def: "Le montant pour entrer dans une partie (cave de cash game) ou un tournoi (droit d'entrée + dotation)." },
  { term: "Call", def: "Suivre : égaler la mise en cours pour rester dans le coup." },
  { term: "Cash game", def: "Partie d'argent où les jetons valent leur valeur réelle et où l'on peut entrer et sortir à tout moment." },
  { term: "Check", def: "Passer son tour sans miser, possible uniquement si personne n'a misé avant vous sur ce tour." },
  { term: "Check-raise", def: "Checker puis relancer après une mise adverse sur le même tour. Mouvement puissant, en valeur ou en bluff." },
  { term: "Cold call", def: "Suivre une relance sans avoir déjà investi dans le pot ce tour-là." },
  { term: "Continuation bet", def: "Mise de continuation : miser au flop après avoir été le relanceur préflop. Souvent abrégée « cbet »." },
  { term: "Cooler", def: "Situation où deux très grosses mains se rencontrent : la perte est quasi inévitable.", example: "Full contre carré : un vrai cooler." },
  { term: "Donk bet", def: "Miser en premier hors de position contre le relanceur préflop, au lieu de checker. Souvent mal vu, parfois efficace." },
  { term: "Draw", def: "Tirage : une main non encore faite mais qui peut s'améliorer (tirage couleur, tirage quinte)." },
  { term: "Equity", def: "Votre part « théorique » du pot, soit votre pourcentage de chances de gagner la main à un instant donné." },
  { term: "Expected value (EV)", def: "Espérance de gain : le résultat moyen d'une décision si on la répétait une infinité de fois. On cherche les décisions « +EV »." },
  { term: "Fish", def: "Joueur faible ou débutant, source de profit pour les autres. Opposé du « requin » (shark)." },
  { term: "Float", def: "Suivre une mise avec une main faible pour bluffer à un tour ultérieur, souvent en position." },
  { term: "Fold", def: "Se coucher : jeter ses cartes et abandonner la main." },
  { term: "Freeroll", def: "Tournoi gratuit avec des gains réels. Désigne aussi une situation où l'on ne peut pas perdre mais où l'on peut gagner plus." },
  { term: "GTO", def: "Game Theory Optimal : stratégie d'équilibre, théoriquement inexploitable, basée sur la théorie des jeux." },
  { term: "Grinder", def: "Joueur régulier qui accumule ses gains patiemment, volume après volume, sur de longues sessions." },
  { term: "Gutshot", def: "Tirage quinte par le ventre : il manque une seule carte au milieu de la suite (4 outs).", example: "Avec 9-8 sur J-10-3, le 7 complète le gutshot." },
  { term: "Hero call", def: "Suivre une grosse mise avec une main médiocre parce qu'on a « lu » un bluff adverse." },
  { term: "ICM", def: "Independent Chip Model : modèle qui convertit les tapis en tournoi en valeur monétaire réelle, crucial en table finale." },
  { term: "Implied odds", def: "Cotes implicites : les gains futurs espérés si on touche son tirage, en plus du pot actuel." },
  { term: "ITM", def: "In The Money : avoir atteint les places payées d'un tournoi." },
  { term: "Kicker", def: "Carte d'appoint qui départage deux mains de même valeur.", example: "A-K et A-Q sur une paire d'As : le Roi (kicker) gagne." },
  { term: "Limp", def: "Entrer dans le coup en suivant simplement la big blind, sans relancer. Généralement déconseillé." },
  { term: "MDF", def: "Minimum Defense Frequency : fréquence minimale à laquelle il faut défendre pour ne pas être exploitable par les bluffs." },
  { term: "Misdeal", def: "Donne erronée (mauvais nombre de cartes, carte exposée...) : les cartes sont reprises et redistribuées." },
  { term: "MTT", def: "Multi-Table Tournament : tournoi sur plusieurs tables qui fusionnent au fil des éliminations." },
  { term: "Muck", def: "Jeter ses cartes face cachée, sans les montrer, au showdown ou en se couchant." },
  { term: "Nuts", def: "La meilleure main possible à un instant donné, imbattable compte tenu du tableau." },
  { term: "Open", def: "Être le premier à relancer préflop (« open-raise »)." },
  { term: "Outs", def: "Les cartes encore dans le jeu qui améliorent votre main.", example: "Un tirage couleur a 9 outs (les cartes restantes de la couleur)." },
  { term: "Overbet", def: "Miser plus que la taille du pot. Mouvement de pression fort, en valeur ou en bluff." },
  { term: "Overcard", def: "Carte plus haute que toutes celles du tableau.", example: "Avec A-K sur un flop 9-7-2, vous avez deux overcards." },
  { term: "Pot", def: "L'ensemble des jetons misés au centre, à remporter par le gagnant de la main." },
  { term: "Pot odds", def: "Cotes du pot : le rapport entre la mise à suivre et la taille du pot, pour juger si un call est rentable." },
  { term: "Position", def: "Votre ordre de parole. « En position » = parler en dernier, un avantage majeur." },
  { term: "Préflop", def: "Le tour d'enchères avant le flop, joué avec seulement ses deux cartes." },
  { term: "Range", def: "L'éventail de toutes les mains qu'un joueur peut avoir dans une situation donnée." },
  { term: "Rake", def: "Commission prélevée par la salle sur chaque pot (cash game) ou via les droits d'entrée (tournoi)." },
  { term: "Raise", def: "Relancer : augmenter la mise en cours." },
  { term: "River", def: "La cinquième et dernière carte commune, suivie du dernier tour d'enchères." },
  { term: "ROI", def: "Return On Investment : rentabilité d'un joueur de tournoi, en pourcentage des buy-ins investis." },
  { term: "Set", def: "Brelan formé avec une paire en main + une troisième carte au tableau. Très bien camouflé." },
  { term: "Set mining", def: "Suivre une relance avec une petite paire dans l'espoir de toucher un brelan au flop." },
  { term: "Shark", def: "Requin : joueur fort et redoutable, qui se « nourrit » des joueurs faibles." },
  { term: "Showdown", def: "L'abattage : le dévoilement des mains à la fin de la main pour désigner le gagnant." },
  { term: "Side pot", def: "Pot annexe créé quand un joueur est all-in pour moins que les autres : il ne peut gagner que le pot principal." },
  { term: "Slow play", def: "Jouer une main forte de façon passive (check, call) pour piéger l'adversaire et l'inciter à miser." },
  { term: "Small blind", def: "La plus petite des deux mises obligatoires, posée à gauche du bouton." },
  { term: "Squeeze", def: "Grosse relance après une ouverture suivie d'au moins un call, pour « compresser » les adversaires et rafler le pot." },
  { term: "Stack", def: "Le tapis : l'ensemble des jetons dont dispose un joueur, souvent mesuré en big blinds." },
  { term: "Straddle", def: "Relance volontaire à l'aveugle avant la donne, généralement du double de la big blind." },
  { term: "Tell", def: "Indice involontaire (geste, regard, hésitation) qui trahit la force de la main d'un joueur." },
  { term: "Tilt", def: "État émotionnel où la frustration fait jouer de façon irrationnelle, après un bad beat par exemple." },
  { term: "Turn", def: "La quatrième carte commune, entre le flop et la river, suivie d'un tour d'enchères." },
  { term: "Value bet", def: "Miser en valeur : miser avec une bonne main pour être suivi par une main moins forte." },
  { term: "Variance", def: "L'amplitude des résultats à court terme due au hasard. Forte variance = gros écarts gain/perte." },
  { term: "VPIP", def: "Voluntarily Put money In Pot : statistique mesurant la fréquence à laquelle un joueur entre volontairement dans les coups." },
  { term: "Wash", def: "Le mélange initial des cartes à plat sur la table, par mouvements circulaires, avant tout autre mélange." },
  { term: "3-bet", def: "La troisième mise d'un tour : une relance qui répond à une première relance (l'open). En valeur ou en bluff.", example: "UTG ouvre à 3 BB, le bouton 3-bet à 9 BB." },
  { term: "4-bet", def: "La relance qui répond à un 3-bet. Souvent le signe d'une main très forte, parfois un bluff calculé." },
  { term: "5-bet", def: "La relance qui suit un 4-bet, généralement synonyme de tapis. Réservée aux situations extrêmes." },
  { term: "Facteur d'agression", def: "Statistique (AF) qui mesure l'agressivité d'un joueur : le rapport entre ses mises ou relances et ses suivis." },
  { term: "Air", def: "Une main sans aucune valeur, ni paire ni tirage. On mise « avec de l'air » quand on bluffe complètement." },
  { term: "Angle shooting", def: "User d'une astuce limite, à la frontière des règles, pour tromper un adversaire. Toléré mais mal vu, à l'opposé du fair-play." },
  { term: "Bankroll", def: "Le capital total qu'un joueur consacre au poker. Une bonne gestion de bankroll évite de « sauter » lors d'une mauvaise série." },
  { term: "Big Slick", def: "Le surnom de la main As-Roi (A-K). Forte main de départ, mais qui ne touche souvent rien au flop." },
  { term: "Blank", def: "Une carte qui ne change rien à la situation (ni tirage, ni amélioration pour personne).", example: "Le turn apporte un 2 de trèfle, un vrai blank." },
  { term: "Texture du board", def: "La nature des cartes communes : sèche (peu de tirages) ou humide (beaucoup de tirages couleur et quinte)." },
  { term: "Bottom pair", def: "Une paire formée avec la carte la plus basse du tableau. Main faible, à jouer avec prudence." },
  { term: "Broadway", def: "Les cartes hautes de 10 à l'As. La suite As-Roi-Dame-Valet-10 est aussi appelée « Broadway »." },
  { term: "Brick", def: "Comme un blank : une carte inutile, qui ne complète aucun tirage. On dit « la river a brické »." },
  { term: "Bust", def: "Être éliminé d'un tournoi (ou ruiné en cash game) après avoir perdu tout son tapis." },
  { term: "Calling station", def: "Joueur qui suit beaucoup trop, sans relancer ni se coucher. Difficile à bluffer, facile à valoriser." },
  { term: "Cap", def: "Le plafond du rake, ou le nombre maximum de relances autorisées sur un tour en limit poker." },
  { term: "Card dead", def: "Traverser une longue période sans recevoir de bonnes mains. « Je suis card dead depuis une heure. »" },
  { term: "Chip leader", def: "Le joueur qui possède le plus gros tapis d'un tournoi à un instant donné." },
  { term: "Chop", def: "Le partage du pot entre plusieurs joueurs à égalité, ou un accord de partage des gains en table finale." },
  { term: "Coin flip", def: "Une situation à environ 50/50, typiquement une paire contre deux cartes hautes (par exemple 8-8 contre A-K)." },
  { term: "Connecteurs", def: "Deux cartes consécutives (par exemple 8-7). Assortis, ce sont les « suited connectors », prisés pour leur potentiel de tirage." },
  { term: "Crying call", def: "Suivre une mise en étant presque sûr d'être battu, mais sans pouvoir se résoudre à se coucher." },
  { term: "Dead money", def: "L'argent déjà dans le pot qui n'appartient plus à personne en particulier, et que les joueurs se disputent." },
  { term: "Deep stack", def: "Un tapis profond, large par rapport aux blindes (souvent 150 BB ou plus). Favorise le jeu post-flop." },
  { term: "Donkey", def: "Terme péjoratif pour un joueur faible qui fait de grosses erreurs. Souvent abrégé « donk »." },
  { term: "Double up", def: "Doubler son tapis en remportant un coup, généralement en gagnant un tapis complet à l'abattage." },
  { term: "Drawing dead", def: "Être sur un tirage qui ne peut plus gagner : même en touchant, on reste battu. La pire situation possible." },
  { term: "Board sec", def: "Un tableau qui n'offre presque aucun tirage (par exemple K-7-2 dépareillé). Favorise le c-bet." },
  { term: "Tapis effectif", def: "Le plus petit des deux tapis en jeu dans un coup. C'est lui qui détermine combien on peut réellement gagner ou perdre." },
  { term: "Family pot", def: "Un pot où presque tous les joueurs de la table participent. Fréquent dans les parties très passives." },
  { term: "Table finale", def: "La dernière table d'un tournoi, où se jouent les places les plus payées. Souvent abrégée « TF »." },
  { term: "Flat call", def: "Se contenter de suivre une relance plutôt que de relancer à son tour, souvent pour cacher la force de sa main." },
  { term: "Flop", def: "Les trois premières cartes communes, dévoilées en même temps après le premier tour d'enchères." },
  { term: "Tirage couleur", def: "Avoir quatre cartes de la même couleur, en attendant la cinquième. Neuf cartes l'améliorent (9 outs)." },
  { term: "Fold equity", def: "La valeur que représente la probabilité de faire coucher l'adversaire. C'est le moteur du bluff et du semi-bluff." },
  { term: "Carte gratuite", def: "Voir la carte suivante sans avoir à payer, parce que tout le monde a checké. Précieux quand on a un tirage." },
  { term: "Freezeout", def: "Un tournoi sans recave : une fois éliminé, c'est terminé. Le format le plus classique." },
  { term: "Full ring", def: "Une table pleine, généralement de 9 ou 10 joueurs, par opposition au 6-max." },
  { term: "Heads-up", def: "Le duel à deux joueurs, soit en partie dédiée, soit à la fin d'un tournoi pour la victoire." },
  { term: "Cartes fermées", def: "Les deux cartes privatives que seul vous voyez. Aussi appelées « hole cards »." },
  { term: "Isolation", def: "Relancer un limpeur pour se retrouver seul contre lui, en position et avec l'initiative. On parle d'« iso-raise »." },
  { term: "Jam", def: "Faire tapis, pousser tous ses jetons. Synonyme de « shove » et d'« all-in »." },
  { term: "Leak", def: "Une fuite dans son jeu : une erreur récurrente qui coûte de l'argent sur le long terme." },
  { term: "Niveau", def: "En tournoi, une période de jeu à blindes fixes. En stratégie, le « niveau » de réflexion (que pense l'adversaire que je pense...)." },
  { term: "Loose", def: "Joueur qui entre dans beaucoup de coups, avec une large sélection de mains. L'opposé de « tight »." },
  { term: "Main faite", def: "Une main déjà complète (paire, suite, couleur...), par opposition à un simple tirage." },
  { term: "Maniac", def: "Joueur ultra-agressif qui relance et bluffe sans cesse. Dangereux mais exploitable avec de la patience." },
  { term: "Min-raise", def: "La relance minimale autorisée : le double de la mise en cours. Souvent utilisée pour contrôler la taille du pot." },
  { term: "Monster", def: "Une main énorme, quasi imbattable, avec laquelle on cherche à maximiser le pot." },
  { term: "Multiway", def: "Un pot disputé par trois joueurs ou plus. Les bluffs y marchent moins, la valeur prime." },
  { term: "Nit", def: "Joueur extrêmement serré et prudent, qui ne joue que les meilleures mains. Facile à lire." },
  { term: "No-limit", def: "La variante où l'on peut miser tous ses jetons à tout moment. Le format roi du Texas Hold'em moderne." },
  { term: "Offsuit", def: "Deux cartes de couleurs différentes (dépareillées). On note par exemple « A-Ko » pour As-Roi offsuit." },
  { term: "Tirage quinte ouvert", def: "Une suite ouverte des deux côtés, par exemple 9-8-7-6 (le 5 ou le 10 complètent). Huit outs." },
  { term: "Orbit", def: "Un tour complet de table, le temps que le bouton revienne à la même place. Sert à mesurer le rythme d'un tournoi." },
  { term: "Hors de position", def: "Devoir parler avant l'adversaire à chaque tour (OOP). Un désavantage majeur." },
  { term: "Surpaire", def: "Une paire servie plus haute que toutes les cartes du tableau (overpair).", example: "Avoir K-K sur un flop 9-7-2." },
  { term: "Passif", def: "Style de jeu qui suit et checke beaucoup, sans miser ni relancer. Souvent peu rentable." },
  { term: "Paire servie", def: "Recevoir une paire dans ses deux cartes (pocket pair), comme une paire de Dames." },
  { term: "Range polarisée", def: "Un éventail composé uniquement de très bonnes mains et de bluffs, sans mains intermédiaires." },
  { term: "Postflop", def: "Toutes les phases qui suivent le flop : flop, turn et river. C'est là que se gagne l'argent." },
  { term: "Pot-limit", def: "La variante où la mise maximale est plafonnée à la taille du pot. Reine du format Omaha (PLO)." },
  { term: "Protection", def: "Miser pour faire coucher des tirages adverses et protéger une main fragile mais en tête." },
  { term: "Rabbit hunting", def: "Demander à voir les cartes qui seraient venues si le coup avait continué. Souvent interdit pour ne pas ralentir le jeu." },
  { term: "Rainbow", def: "Un flop de trois couleurs différentes, qui ne permet aucun tirage couleur. Très sec." },
  { term: "Rakeback", def: "Le reversement d'une partie du rake payé, via un programme de fidélité de la salle." },
  { term: "Recave", def: "Remettre des jetons sur la table pour reconstituer son tapis, entre deux mains en cash game." },
  { term: "Représenter", def: "Jouer de façon à faire croire qu'on a une main précise, qu'on l'ait réellement ou non." },
  { term: "Reverse implied odds", def: "Le risque de perdre gros en touchant son tirage tout en restant battu par une main encore meilleure." },
  { term: "Rock", def: "Joueur très serré et prévisible, comme un nit. On peut lui voler ses blindes mais pas le payer léger." },
  { term: "Run it twice", def: "Quand deux joueurs sont à tapis, distribuer les cartes restantes deux fois pour réduire la variance, chacun gagnant la moitié à chaque fois." },
  { term: "Runner-runner", def: "Compléter une main grâce aux deux dernières cartes (turn ET river), un tirage par la « porte de derrière »." },
  { term: "Satellite", def: "Un tournoi dont les places payées sont des tickets pour un tournoi plus cher, au lieu d'argent." },
  { term: "Scare card", def: "Une carte effrayante qui menace votre main et fait peur, comme un As ou une troisième carte de la même couleur." },
  { term: "Semi-bluff", def: "Miser ou relancer avec un tirage : on peut gagner tout de suite en faisant coucher, ou plus tard en touchant." },
  { term: "Petit tapis", def: "Un tapis court (short stack), souvent sous 20 BB, qui impose un jeu en tapis ou poubelle (push/fold)." },
  { term: "Shove", def: "Faire tapis. Synonyme de « jam » et d'« all-in »." },
  { term: "Slowroll", def: "Attendre exprès avant de retourner une main gagnante, pour faire croire à l'adversaire qu'il a gagné. Le pire manque de respect au poker." },
  { term: "Snap call", def: "Suivre instantanément, sans réfléchir, parce que la décision est évidente." },
  { term: "Splash the pot", def: "Jeter ses jetons en désordre au milieu du pot au lieu de les poser proprement. Interdit : le croupier ne peut plus compter la mise." },
  { term: "Stakes", def: "Le niveau d'enjeux d'une partie, défini par ses blindes (micro, low, mid, high stakes)." },
  { term: "Vol de blindes", def: "Relancer en position tardive avec une main quelconque pour rafler les blindes sans combat." },
  { term: "String bet", def: "Miser en deux mouvements au lieu d'un (poser, puis rajouter). Interdit : seule la première partie compte." },
  { term: "Assorti", def: "Deux cartes de la même couleur (suited), qui ouvrent la possibilité d'une couleur." },
  { term: "Tank", def: "Prendre un long moment de réflexion avant d'agir. « Il est dans le tank depuis deux minutes. »" },
  { term: "Tight", def: "Joueur serré, qui sélectionne fortement ses mains de départ. L'opposé de « loose »." },
  { term: "Top paire", def: "Une paire formée avec la plus haute carte du tableau. Une main correcte mais à manier selon le kicker." },
  { term: "Trap", def: "Piéger : jouer une main très forte de façon passive pour inciter l'adversaire à miser dans le vide." },
  { term: "Underdog", def: "Le joueur défavori dans un coup, celui qui a la plus petite équité." },
  { term: "Upswing / Downswing", def: "Une longue période de gains (upswing) ou de pertes (downswing) due à la variance." },
  { term: "Villain", def: "Terme générique pour désigner l'adversaire dans l'analyse d'une main (par opposition à « hero », vous)." },
  { term: "Board humide", def: "Un tableau riche en tirages (couleur, quinte), dangereux et propice à l'action. L'opposé du board sec." },
  { term: "Whale", def: "Un joueur très fortuné et faible, source de profit majeure. La « baleine » que tout le monde veut à sa table." },
  { term: "La roue", def: "La plus petite suite possible, A-2-3-4-5, où l'As compte comme un 1 (the wheel)." },
];
