/**
 * Glossaire poker — dictionnaire des termes, défini simplement avec exemples.
 * Lot de départ (à étendre vers 300+ termes). Trié alphabétiquement à l'affichage.
 */

export type Term = {
  term: string;
  def: string;
  example?: string;
};

export const GLOSSARY: Term[] = [
  { term: "Action", def: "Le fait de miser, relancer ou suivre. Désigne aussi l'animation d'une table : « il y a de l'action »." },
  { term: "Add-on", def: "Achat de jetons supplémentaires proposé une seule fois dans certains tournois, généralement à la fin de la période de recave.", example: "À la pause, tous les joueurs prennent l'add-on de 3000 jetons." },
  { term: "All-in", def: "Miser la totalité de ses jetons. On dit aussi « faire tapis ».", example: "Avec As-Roi, il pousse all-in pour 40 big blinds." },
  { term: "Ante", def: "Petite mise obligatoire payée par tous les joueurs avant la distribution, surtout en tournoi, pour gonfler le pot." },
  { term: "Backdoor", def: "Tirage « par la porte de derrière » qui nécessite d'améliorer au turn ET à la river pour se compléter.", example: "Un backdoor flush : deux cartes de la couleur au flop, il en faut encore deux." },
  { term: "Bad beat", def: "Perdre une main qu'on était très largement favori à gagner, à cause d'une carte improbable.", example: "Son brelan d'As battu par une couleur rentrée à la river : le bad beat classique." },
  { term: "Barrel", def: "Continuer à miser sur plusieurs tours consécutifs, souvent en bluff. « Double barrel » = miser flop et turn." },
  { term: "Bet", def: "Être le premier à miser sur un tour d'enchères." },
  { term: "Big blind", def: "La mise obligatoire pleine, posée à gauche de la small blind. Sert d'unité de mesure des tapis (en BB)." },
  { term: "Blocker", def: "Carte que vous détenez et qui réduit les combinaisons possibles de l'adversaire.", example: "Avoir l'As de pique « bloque » la couleur max adverse." },
  { term: "Bluff", def: "Miser ou relancer avec une main faible pour faire coucher une meilleure main." },
  { term: "Board", def: "Le tableau : l'ensemble des cartes communes posées au centre (flop, turn, river)." },
  { term: "Bounty", def: "Prime mise sur la tête d'un joueur dans un tournoi « knockout » : l'éliminer rapporte un bonus." },
  { term: "Bubble", def: "La place juste avant les places payées. Être « sur la bulle », c'est risquer d'être éliminé sans rien gagner." },
  { term: "Button", def: "Le bouton du donneur. Indique le joueur en dernière position post-flop, la meilleure place à la table." },
  { term: "Buy-in", def: "Le montant pour entrer dans une partie (cave de cash game) ou un tournoi (droit d'entrée + dotation)." },
  { term: "Call", def: "Suivre : égaler la mise en cours pour rester dans le coup." },
  { term: "Cash game", def: "Partie d'argent où les jetons valent leur valeur réelle et où l'on peut entrer et sortir à tout moment." },
  { term: "Check", def: "Passer son tour sans miser, possible uniquement si personne n'a misé avant vous sur ce tour." },
  { term: "Check-raise", def: "Checker puis relancer après une mise adverse sur le même tour. Mouvement puissant, en valeur ou en bluff." },
  { term: "Cold call", def: "Suivre une relance sans avoir déjà investi dans le pot ce tour-là." },
  { term: "Continuation bet", def: "Mise de continuation : miser au flop après avoir été le relanceur préflop. Souvent abrégée « cbet »." },
  { term: "Cooler", def: "Situation où deux très grosses mains se rencontrent : la perte est quasi inévitable.", example: "Full contre carré : un vrai cooler." },
  { term: "Donk bet", def: "Miser en premier hors de position contre le relanceur préflop, au lieu de checker. Souvent mal vu, parfois efficace." },
  { term: "Draw", def: "Tirage : une main non encore faite mais qui peut s'améliorer (tirage couleur, tirage quinte)." },
  { term: "Equity", def: "Votre part « théorique » du pot, soit votre pourcentage de chances de gagner la main à un instant donné." },
  { term: "Expected value (EV)", def: "Espérance de gain : le résultat moyen d'une décision si on la répétait une infinité de fois. On cherche les décisions « +EV »." },
  { term: "Fish", def: "Joueur faible ou débutant, source de profit pour les autres. Opposé du « requin » (shark)." },
  { term: "Float", def: "Suivre une mise avec une main faible pour bluffer à un tour ultérieur, souvent en position." },
  { term: "Fold", def: "Se coucher : jeter ses cartes et abandonner la main." },
  { term: "Freeroll", def: "Tournoi gratuit avec des gains réels. Désigne aussi une situation où l'on ne peut pas perdre mais où l'on peut gagner plus." },
  { term: "GTO", def: "Game Theory Optimal : stratégie d'équilibre, théoriquement inexploitable, basée sur la théorie des jeux." },
  { term: "Grinder", def: "Joueur régulier qui accumule ses gains patiemment, volume après volume, sur de longues sessions." },
  { term: "Gutshot", def: "Tirage quinte par le ventre : il manque une seule carte au milieu de la suite (4 outs).", example: "Avec 9-8 sur J-10-3, le 7 complète le gutshot." },
  { term: "Hero call", def: "Suivre une grosse mise avec une main médiocre parce qu'on a « lu » un bluff adverse." },
  { term: "ICM", def: "Independent Chip Model : modèle qui convertit les tapis en tournoi en valeur monétaire réelle, crucial en table finale." },
  { term: "Implied odds", def: "Cotes implicites : les gains futurs espérés si on touche son tirage, en plus du pot actuel." },
  { term: "ITM", def: "In The Money : avoir atteint les places payées d'un tournoi." },
  { term: "Kicker", def: "Carte d'appoint qui départage deux mains de même valeur.", example: "A-K et A-Q sur une paire d'As : le Roi (kicker) gagne." },
  { term: "Limp", def: "Entrer dans le coup en suivant simplement la big blind, sans relancer. Généralement déconseillé." },
  { term: "MDF", def: "Minimum Defense Frequency : fréquence minimale à laquelle il faut défendre pour ne pas être exploitable par les bluffs." },
  { term: "Misdeal", def: "Donne erronée (mauvais nombre de cartes, carte exposée...) : les cartes sont reprises et redistribuées." },
  { term: "MTT", def: "Multi-Table Tournament : tournoi sur plusieurs tables qui fusionnent au fil des éliminations." },
  { term: "Muck", def: "Jeter ses cartes face cachée, sans les montrer, au showdown ou en se couchant." },
  { term: "Nuts", def: "La meilleure main possible à un instant donné, imbattable compte tenu du tableau." },
  { term: "Open", def: "Être le premier à relancer préflop (« open-raise »)." },
  { term: "Outs", def: "Les cartes encore dans le jeu qui améliorent votre main.", example: "Un tirage couleur a 9 outs (les cartes restantes de la couleur)." },
  { term: "Overbet", def: "Miser plus que la taille du pot. Mouvement de pression fort, en valeur ou en bluff." },
  { term: "Overcard", def: "Carte plus haute que toutes celles du tableau.", example: "Avec A-K sur un flop 9-7-2, vous avez deux overcards." },
  { term: "Pot", def: "L'ensemble des jetons misés au centre, à remporter par le gagnant de la main." },
  { term: "Pot odds", def: "Cotes du pot : le rapport entre la mise à suivre et la taille du pot, pour juger si un call est rentable." },
  { term: "Position", def: "Votre ordre de parole. « En position » = parler en dernier, un avantage majeur." },
  { term: "Préflop", def: "Le tour d'enchères avant le flop, joué avec seulement ses deux cartes." },
  { term: "Range", def: "L'éventail de toutes les mains qu'un joueur peut avoir dans une situation donnée." },
  { term: "Rake", def: "Commission prélevée par la salle sur chaque pot (cash game) ou via les droits d'entrée (tournoi)." },
  { term: "Raise", def: "Relancer : augmenter la mise en cours." },
  { term: "River", def: "La cinquième et dernière carte commune, suivie du dernier tour d'enchères." },
  { term: "ROI", def: "Return On Investment : rentabilité d'un joueur de tournoi, en pourcentage des buy-ins investis." },
  { term: "Set", def: "Brelan formé avec une paire en main + une troisième carte au tableau. Très bien camouflé." },
  { term: "Set mining", def: "Suivre une relance avec une petite paire dans l'espoir de toucher un brelan au flop." },
  { term: "Shark", def: "Requin : joueur fort et redoutable, qui se « nourrit » des joueurs faibles." },
  { term: "Showdown", def: "L'abattage : le dévoilement des mains à la fin de la main pour désigner le gagnant." },
  { term: "Side pot", def: "Pot annexe créé quand un joueur est all-in pour moins que les autres : il ne peut gagner que le pot principal." },
  { term: "Slow play", def: "Jouer une main forte de façon passive (check, call) pour piéger l'adversaire et l'inciter à miser." },
  { term: "Small blind", def: "La plus petite des deux mises obligatoires, posée à gauche du bouton." },
  { term: "Squeeze", def: "Grosse relance après une ouverture suivie d'au moins un call, pour « compresser » les adversaires et rafler le pot." },
  { term: "Stack", def: "Le tapis : l'ensemble des jetons dont dispose un joueur, souvent mesuré en big blinds." },
  { term: "Straddle", def: "Relance volontaire à l'aveugle avant la donne, généralement du double de la big blind." },
  { term: "Tell", def: "Indice involontaire (geste, regard, hésitation) qui trahit la force de la main d'un joueur." },
  { term: "Tilt", def: "État émotionnel où la frustration fait jouer de façon irrationnelle, après un bad beat par exemple." },
  { term: "Turn", def: "La quatrième carte commune, entre le flop et la river, suivie d'un tour d'enchères." },
  { term: "Value bet", def: "Miser en valeur : miser avec une bonne main pour être suivi par une main moins forte." },
  { term: "Variance", def: "L'amplitude des résultats à court terme due au hasard. Forte variance = gros écarts gain/perte." },
  { term: "VPIP", def: "Voluntarily Put money In Pot : statistique mesurant la fréquence à laquelle un joueur entre volontairement dans les coups." },
  { term: "Wash", def: "Le mélange initial des cartes à plat sur la table, par mouvements circulaires, avant tout autre mélange." },
];
