/**
 * Glossaire poker, dictionnaire des termes, défini simplement avec exemples.
 * Lot de départ (à étendre vers 300+ termes). Trié alphabétiquement à l'affichage.
 */

export type Term = {
  term: string;
  def: string;
  example?: string;
};

export const GLOSSARY: Term[] = [
  { term: "Action", def: "Le fait de miser, relancer ou suivre. Désigne aussi l'animation d'une table : « il y a de l'action »." },
  { term: "Add-on", def: "Achat de jetons supplémentaires proposé une seule fois dans certains tournois, généralement à la fin de la période de recave.", example: "À la pause, tous les joueurs prennent l'add-on de 3000 jetons." },
  { term: "All-in", def: "Miser la totalité de ses jetons. On dit aussi « faire tapis ».", example: "Avec As-Roi, il pousse all-in pour 40 big blinds." },
  { term: "Ante", def: "Petite mise obligatoire payée par tous les joueurs avant la distribution, surtout en tournoi, pour gonfler le pot." },
  { term: "Backdoor", def: "Tirage « par la porte de derrière » qui nécessite d'améliorer au turn ET à la river pour se compléter.", example: "Un backdoor flush : deux cartes de la couleur au flop, il en faut encore deux." },
  { term: "Bad beat", def: "Perdre une main qu'on était très largement favori à gagner, à cause d'une carte improbable.", example: "Son brelan d'As battu par une couleur rentrée à la river : le bad beat classique." },
  { term: "Barrel", def: "Continuer à miser sur plusieurs tours consécutifs, souvent en bluff. « Double barrel » = miser flop et turn." },
  { term: "Bet", def: "Être le premier à miser sur un tour d'enchères." },
  { term: "Big blind", def: "La mise obligatoire pleine, posée à gauche de la small blind. Sert d'unité de mesure des tapis (en BB)." },
  { term: "Blocker", def: "Carte que vous détenez et qui réduit les combinaisons possibles de l'adversaire.", example: "Avoir l'As de pique « bloque » la couleur max adverse." },
  { term: "Bluff", def: "Miser ou relancer avec une main faible pour faire coucher une meilleure main." },
  { term: "Board", def: "Le tableau : l'ensemble des cartes communes posées au centre (flop, turn, river)." },
  { term: "Bounty", def: "Prime mise sur la tête d'un joueur dans un tournoi « knockout » : l'éliminer rapporte un bonus." },
  { term: "Bubble", def: "La place juste avant les places payées. Être « sur la bulle », c'est risquer d'être éliminé sans rien gagner." },
  { term: "Button", def: "Le bouton du donneur. Indique le joueur en dernière position post-flop, la meilleure place à la table." },
  { term: "Buy-in", def: "Le montant pour entrer dans une partie (cave de cash game) ou un tournoi (droit d'entrée + dotation)." },
  { term: "Call", def: "Suivre : égaler la mise en cours pour rester dans le coup." },
  { term: "Cash game", def: "Partie d'argent où les jetons valent leur valeur réelle et où l'on peut entrer et sortir à tout moment." },
  { term: "Check", def: "Passer son tour sans miser, possible uniquement si personne n'a misé avant vous sur ce tour." },
  { term: "Check-raise", def: "Checker puis relancer après une mise adverse sur le même tour. Mouvement puissant, en valeur ou en bluff." },
  { term: "Cold call", def: "Suivre une relance sans avoir déjà investi dans le pot ce tour-là." },
  { term: "Continuation bet", def: "Mise de continuation : miser au flop après avoir été le relanceur préflop. Souvent abrégée « cbet »." },
  { term: "Cooler", def: "Situation où deux très grosses mains se rencontrent : la perte est quasi inévitable.", example: "Full contre carré : un vrai cooler." },
  { term: "Donk bet", def: "Miser en premier hors de position contre le relanceur préflop, au lieu de checker. Souvent mal vu, parfois efficace." },
  { term: "Draw", def: "Tirage : une main non encore faite mais qui peut s'améliorer (tirage couleur, tirage quinte)." },
  { term: "Equity", def: "Votre part « théorique » du pot, soit votre pourcentage de chances de gagner la main à un instant donné." },
  { term: "Expected value (EV)", def: "Espérance de gain : le résultat moyen d'une décision si on la répétait une infinité de fois. On cherche les décisions « +EV »." },
  { term: "Fish", def: "Joueur faible ou débutant, source de profit pour les autres. Opposé du « requin » (shark)." },
  { term: "Float", def: "Suivre une mise avec une main faible pour bluffer à un tour ultérieur, souvent en position." },
  { term: "Fold", def: "Se coucher : jeter ses cartes et abandonner la main." },
  { term: "Freeroll", def: "Tournoi gratuit avec des gains réels. Désigne aussi une situation où l'on ne peut pas perdre mais où l'on peut gagner plus." },
  { term: "GTO", def: "Game Theory Optimal : stratégie d'équilibre, théoriquement inexploitable, basée sur la théorie des jeux." },
  { term: "Grinder", def: "Joueur régulier qui accumule ses gains patiemment, volume après volume, sur de longues sessions." },
  { term: "Gutshot", def: "Tirage quinte par le ventre : il manque une seule carte au milieu de la suite (4 outs).", example: "Avec 9-8 sur J-10-3, le 7 complète le gutshot." },
  { term: "Hero call", def: "Suivre une grosse mise avec une main médiocre parce qu'on a « lu » un bluff adverse." },
  { term: "ICM", def: "Independent Chip Model : modèle qui convertit les tapis en tournoi en valeur monétaire réelle, crucial en table finale." },
  { term: "Implied odds", def: "Cotes implicites : les gains futurs espérés si on touche son tirage, en plus du pot actuel." },
  { term: "ITM", def: "In The Money : avoir atteint les places payées d'un tournoi." },
  { term: "Kicker", def: "Carte d'appoint qui départage deux mains de même valeur.", example: "A-K et A-Q sur une paire d'As : le Roi (kicker) gagne." },
  { term: "Limp", def: "Entrer dans le coup en suivant simplement la big blind, sans relancer. Généralement déconseillé." },
  { term: "MDF", def: "Minimum Defense Frequency : fréquence minimale à laquelle il faut défendre pour ne pas être exploitable par les bluffs." },
  { term: "Misdeal", def: "Donne erronée (mauvais nombre de cartes, carte exposée...) : les cartes sont reprises et redistribuées." },
  { term: "MTT", def: "Multi-Table Tournament : tournoi sur plusieurs tables qui fusionnent au fil des éliminations." },
  { term: "Muck", def: "Jeter ses cartes face cachée, sans les montrer, au showdown ou en se couchant." },
  { term: "Nuts", def: "La meilleure main possible à un instant donné, imbattable compte tenu du tableau." },
  { term: "Open", def: "Être le premier à relancer préflop (« open-raise »)." },
  { term: "Outs", def: "Les cartes encore dans le jeu qui améliorent votre main.", example: "Un tirage couleur a 9 outs (les cartes restantes de la couleur)." },
  { term: "Overbet", def: "Miser plus que la taille du pot. Mouvement de pression fort, en valeur ou en bluff." },
  { term: "Overcard", def: "Carte plus haute que toutes celles du tableau.", example: "Avec A-K sur un flop 9-7-2, vous avez deux overcards." },
  { term: "Pot", def: "L'ensemble des jetons misés au centre, à remporter par le gagnant de la main." },
  { term: "Pot odds", def: "Cotes du pot : le rapport entre la mise à suivre et la taille du pot, pour juger si un call est rentable." },
  { term: "Position", def: "Votre ordre de parole. « En position » = parler en dernier, un avantage majeur." },
  { term: "Préflop", def: "Le tour d'enchères avant le flop, joué avec seulement ses deux cartes." },
  { term: "Range", def: "L'éventail de toutes les mains qu'un joueur peut avoir dans une situation donnée." },
  { term: "Rake", def: "Commission prélevée par la salle sur chaque pot (cash game) ou via les droits d'entrée (tournoi)." },
  { term: "Raise", def: "Relancer : augmenter la mise en cours." },
  { term: "River", def: "La cinquième et dernière carte commune, suivie du dernier tour d'enchères." },
  { term: "ROI", def: "Return On Investment : rentabilité d'un joueur de tournoi, en pourcentage des buy-ins investis." },
  { term: "Set", def: "Brelan formé avec une paire en main + une troisième carte au tableau. Très bien camouflé." },
  { term: "Set mining", def: "Suivre une relance avec une petite paire dans l'espoir de toucher un brelan au flop." },
  { term: "Shark", def: "Requin : joueur fort et redoutable, qui se « nourrit » des joueurs faibles." },
  { term: "Showdown", def: "L'abattage : le dévoilement des mains à la fin de la main pour désigner le gagnant." },
  { term: "Side pot", def: "Pot annexe créé quand un joueur est all-in pour moins que les autres : il ne peut gagner que le pot principal." },
  { term: "Slow play", def: "Jouer une main forte de façon passive (check, call) pour piéger l'adversaire et l'inciter à miser." },
  { term: "Small blind", def: "La plus petite des deux mises obligatoires, posée à gauche du bouton." },
  { term: "Squeeze", def: "Grosse relance après une ouverture suivie d'au moins un call, pour « compresser » les adversaires et rafler le pot." },
  { term: "Stack", def: "Le tapis : l'ensemble des jetons dont dispose un joueur, souvent mesuré en big blinds." },
  { term: "Straddle", def: "Relance volontaire à l'aveugle avant la donne, généralement du double de la big blind." },
  { term: "Tell", def: "Indice involontaire (geste, regard, hésitation) qui trahit la force de la main d'un joueur." },
  { term: "Tilt", def: "État émotionnel où la frustration fait jouer de façon irrationnelle, après un bad beat par exemple." },
  { term: "Turn", def: "La quatrième carte commune, entre le flop et la river, suivie d'un tour d'enchères." },
  { term: "Value bet", def: "Miser en valeur : miser avec une bonne main pour être suivi par une main moins forte." },
  { term: "Variance", def: "L'amplitude des résultats à court terme due au hasard. Forte variance = gros écarts gain/perte." },
  { term: "VPIP", def: "Voluntarily Put money In Pot : statistique mesurant la fréquence à laquelle un joueur entre volontairement dans les coups." },
  { term: "Wash", def: "Le mélange initial des cartes à plat sur la table, par mouvements circulaires, avant tout autre mélange." },
  { term: "3-bet", def: "La troisième mise d'un tour : une relance qui répond à une première relance (l'open). En valeur ou en bluff.", example: "UTG ouvre à 3 BB, le bouton 3-bet à 9 BB." },
  { term: "4-bet", def: "La relance qui répond à un 3-bet. Souvent le signe d'une main très forte, parfois un bluff calculé." },
  { term: "5-bet", def: "La relance qui suit un 4-bet, généralement synonyme de tapis. Réservée aux situations extrêmes." },
  { term: "Facteur d'agression", def: "Statistique (AF) qui mesure l'agressivité d'un joueur : le rapport entre ses mises ou relances et ses suivis." },
  { term: "Air", def: "Une main sans aucune valeur, ni paire ni tirage. On mise « avec de l'air » quand on bluffe complètement." },
  { term: "Angle shooting", def: "User d'une astuce limite, à la frontière des règles, pour tromper un adversaire. Toléré mais mal vu, à l'opposé du fair-play." },
  { term: "Bankroll", def: "Le capital total qu'un joueur consacre au poker. Une bonne gestion de bankroll évite de « sauter » lors d'une mauvaise série." },
  { term: "Big Slick", def: "Le surnom de la main As-Roi (A-K). Forte main de départ, mais qui ne touche souvent rien au flop." },
  { term: "Blank", def: "Une carte qui ne change rien à la situation (ni tirage, ni amélioration pour personne).", example: "Le turn apporte un 2 de trèfle, un vrai blank." },
  { term: "Texture du board", def: "La nature des cartes communes : sèche (peu de tirages) ou humide (beaucoup de tirages couleur et quinte)." },
  { term: "Bottom pair", def: "Une paire formée avec la carte la plus basse du tableau. Main faible, à jouer avec prudence." },
  { term: "Broadway", def: "Les cartes hautes de 10 à l'As. La suite As-Roi-Dame-Valet-10 est aussi appelée « Broadway »." },
  { term: "Brick", def: "Comme un blank : une carte inutile, qui ne complète aucun tirage. On dit « la river a brické »." },
  { term: "Bust", def: "Être éliminé d'un tournoi (ou ruiné en cash game) après avoir perdu tout son tapis." },
  { term: "Calling station", def: "Joueur qui suit beaucoup trop, sans relancer ni se coucher. Difficile à bluffer, facile à valoriser." },
  { term: "Cap", def: "Le plafond du rake, ou le nombre maximum de relances autorisées sur un tour en limit poker." },
  { term: "Card dead", def: "Traverser une longue période sans recevoir de bonnes mains. « Je suis card dead depuis une heure. »" },
  { term: "Chip leader", def: "Le joueur qui possède le plus gros tapis d'un tournoi à un instant donné." },
  { term: "Chop", def: "Le partage du pot entre plusieurs joueurs à égalité, ou un accord de partage des gains en table finale." },
  { term: "Coin flip", def: "Une situation à environ 50/50, typiquement une paire contre deux cartes hautes (par exemple 8-8 contre A-K)." },
  { term: "Connecteurs", def: "Deux cartes consécutives (par exemple 8-7). Assortis, ce sont les « suited connectors », prisés pour leur potentiel de tirage." },
  { term: "Crying call", def: "Suivre une mise en étant presque sûr d'être battu, mais sans pouvoir se résoudre à se coucher." },
  { term: "Dead money", def: "L'argent déjà dans le pot qui n'appartient plus à personne en particulier, et que les joueurs se disputent." },
  { term: "Deep stack", def: "Un tapis profond, large par rapport aux blindes (souvent 150 BB ou plus). Favorise le jeu post-flop." },
  { term: "Donkey", def: "Terme péjoratif pour un joueur faible qui fait de grosses erreurs. Souvent abrégé « donk »." },
  { term: "Double up", def: "Doubler son tapis en remportant un coup, généralement en gagnant un tapis complet à l'abattage." },
  { term: "Drawing dead", def: "Être sur un tirage qui ne peut plus gagner : même en touchant, on reste battu. La pire situation possible." },
  { term: "Board sec", def: "Un tableau qui n'offre presque aucun tirage (par exemple K-7-2 dépareillé). Favorise le c-bet." },
  { term: "Tapis effectif", def: "Le plus petit des deux tapis en jeu dans un coup. C'est lui qui détermine combien on peut réellement gagner ou perdre." },
  { term: "Family pot", def: "Un pot où presque tous les joueurs de la table participent. Fréquent dans les parties très passives." },
  { term: "Table finale", def: "La dernière table d'un tournoi, où se jouent les places les plus payées. Souvent abrégée « TF »." },
  { term: "Flat call", def: "Se contenter de suivre une relance plutôt que de relancer à son tour, souvent pour cacher la force de sa main." },
  { term: "Flop", def: "Les trois premières cartes communes, dévoilées en même temps après le premier tour d'enchères." },
  { term: "Tirage couleur", def: "Avoir quatre cartes de la même couleur, en attendant la cinquième. Neuf cartes l'améliorent (9 outs)." },
  { term: "Fold equity", def: "La valeur que représente la probabilité de faire coucher l'adversaire. C'est le moteur du bluff et du semi-bluff." },
  { term: "Carte gratuite", def: "Voir la carte suivante sans avoir à payer, parce que tout le monde a checké. Précieux quand on a un tirage." },
  { term: "Freezeout", def: "Un tournoi sans recave : une fois éliminé, c'est terminé. Le format le plus classique." },
  { term: "Full ring", def: "Une table pleine, généralement de 9 ou 10 joueurs, par opposition au 6-max." },
  { term: "Heads-up", def: "Le duel à deux joueurs, soit en partie dédiée, soit à la fin d'un tournoi pour la victoire." },
  { term: "Cartes fermées", def: "Les deux cartes privatives que seul vous voyez. Aussi appelées « hole cards »." },
  { term: "Isolation", def: "Relancer un limpeur pour se retrouver seul contre lui, en position et avec l'initiative. On parle d'« iso-raise »." },
  { term: "Jam", def: "Faire tapis, pousser tous ses jetons. Synonyme de « shove » et d'« all-in »." },
  { term: "Leak", def: "Une fuite dans son jeu : une erreur récurrente qui coûte de l'argent sur le long terme." },
  { term: "Niveau", def: "En tournoi, une période de jeu à blindes fixes. En stratégie, le « niveau » de réflexion (que pense l'adversaire que je pense...)." },
  { term: "Loose", def: "Joueur qui entre dans beaucoup de coups, avec une large sélection de mains. L'opposé de « tight »." },
  { term: "Main faite", def: "Une main déjà complète (paire, suite, couleur...), par opposition à un simple tirage." },
  { term: "Maniac", def: "Joueur ultra-agressif qui relance et bluffe sans cesse. Dangereux mais exploitable avec de la patience." },
  { term: "Min-raise", def: "La relance minimale autorisée : le double de la mise en cours. Souvent utilisée pour contrôler la taille du pot." },
  { term: "Monster", def: "Une main énorme, quasi imbattable, avec laquelle on cherche à maximiser le pot." },
  { term: "Multiway", def: "Un pot disputé par trois joueurs ou plus. Les bluffs y marchent moins, la valeur prime." },
  { term: "Nit", def: "Joueur extrêmement serré et prudent, qui ne joue que les meilleures mains. Facile à lire." },
  { term: "No-limit", def: "La variante où l'on peut miser tous ses jetons à tout moment. Le format roi du Texas Hold'em moderne." },
  { term: "Offsuit", def: "Deux cartes de couleurs différentes (dépareillées). On note par exemple « A-Ko » pour As-Roi offsuit." },
  { term: "Tirage quinte ouvert", def: "Une suite ouverte des deux côtés, par exemple 9-8-7-6 (le 5 ou le 10 complètent). Huit outs." },
  { term: "Orbit", def: "Un tour complet de table, le temps que le bouton revienne à la même place. Sert à mesurer le rythme d'un tournoi." },
  { term: "Hors de position", def: "Devoir parler avant l'adversaire à chaque tour (OOP). Un désavantage majeur." },
  { term: "Surpaire", def: "Une paire servie plus haute que toutes les cartes du tableau (overpair).", example: "Avoir K-K sur un flop 9-7-2." },
  { term: "Passif", def: "Style de jeu qui suit et checke beaucoup, sans miser ni relancer. Souvent peu rentable." },
  { term: "Paire servie", def: "Recevoir une paire dans ses deux cartes (pocket pair), comme une paire de Dames." },
  { term: "Range polarisée", def: "Un éventail composé uniquement de très bonnes mains et de bluffs, sans mains intermédiaires." },
  { term: "Postflop", def: "Toutes les phases qui suivent le flop : flop, turn et river. C'est là que se gagne l'argent." },
  { term: "Pot-limit", def: "La variante où la mise maximale est plafonnée à la taille du pot. Reine du format Omaha (PLO)." },
  { term: "Protection", def: "Miser pour faire coucher des tirages adverses et protéger une main fragile mais en tête." },
  { term: "Rabbit hunting", def: "Demander à voir les cartes qui seraient venues si le coup avait continué. Souvent interdit pour ne pas ralentir le jeu." },
  { term: "Rainbow", def: "Un flop de trois couleurs différentes, qui ne permet aucun tirage couleur. Très sec." },
  { term: "Rakeback", def: "Le reversement d'une partie du rake payé, via un programme de fidélité de la salle." },
  { term: "Recave", def: "Remettre des jetons sur la table pour reconstituer son tapis, entre deux mains en cash game." },
  { term: "Représenter", def: "Jouer de façon à faire croire qu'on a une main précise, qu'on l'ait réellement ou non." },
  { term: "Reverse implied odds", def: "Le risque de perdre gros en touchant son tirage tout en restant battu par une main encore meilleure." },
  { term: "Rock", def: "Joueur très serré et prévisible, comme un nit. On peut lui voler ses blindes mais pas le payer léger." },
  { term: "Run it twice", def: "Quand deux joueurs sont à tapis, distribuer les cartes restantes deux fois pour réduire la variance, chacun gagnant la moitié à chaque fois." },
  { term: "Runner-runner", def: "Compléter une main grâce aux deux dernières cartes (turn ET river), un tirage par la « porte de derrière »." },
  { term: "Satellite", def: "Un tournoi dont les places payées sont des tickets pour un tournoi plus cher, au lieu d'argent." },
  { term: "Scare card", def: "Une carte effrayante qui menace votre main et fait peur, comme un As ou une troisième carte de la même couleur." },
  { term: "Semi-bluff", def: "Miser ou relancer avec un tirage : on peut gagner tout de suite en faisant coucher, ou plus tard en touchant." },
  { term: "Petit tapis", def: "Un tapis court (short stack), souvent sous 20 BB, qui impose un jeu en tapis ou poubelle (push/fold)." },
  { term: "Shove", def: "Faire tapis. Synonyme de « jam » et d'« all-in »." },
  { term: "Slowroll", def: "Attendre exprès avant de retourner une main gagnante, pour faire croire à l'adversaire qu'il a gagné. Le pire manque de respect au poker." },
  { term: "Snap call", def: "Suivre instantanément, sans réfléchir, parce que la décision est évidente." },
  { term: "Splash the pot", def: "Jeter ses jetons en désordre au milieu du pot au lieu de les poser proprement. Interdit : le croupier ne peut plus compter la mise." },
  { term: "Stakes", def: "Le niveau d'enjeux d'une partie, défini par ses blindes (micro, low, mid, high stakes)." },
  { term: "Vol de blindes", def: "Relancer en position tardive avec une main quelconque pour rafler les blindes sans combat." },
  { term: "String bet", def: "Miser en deux mouvements au lieu d'un (poser, puis rajouter). Interdit : seule la première partie compte." },
  { term: "Assorti", def: "Deux cartes de la même couleur (suited), qui ouvrent la possibilité d'une couleur." },
  { term: "Tank", def: "Prendre un long moment de réflexion avant d'agir. « Il est dans le tank depuis deux minutes. »" },
  { term: "Tight", def: "Joueur serré, qui sélectionne fortement ses mains de départ. L'opposé de « loose »." },
  { term: "Top paire", def: "Une paire formée avec la plus haute carte du tableau. Une main correcte mais à manier selon le kicker." },
  { term: "Trap", def: "Piéger : jouer une main très forte de façon passive pour inciter l'adversaire à miser dans le vide." },
  { term: "Underdog", def: "Le joueur défavori dans un coup, celui qui a la plus petite équité." },
  { term: "Upswing / Downswing", def: "Une longue période de gains (upswing) ou de pertes (downswing) due à la variance." },
  { term: "Villain", def: "Terme générique pour désigner l'adversaire dans l'analyse d'une main (par opposition à « hero », vous)." },
  { term: "Board humide", def: "Un tableau riche en tirages (couleur, quinte), dangereux et propice à l'action. L'opposé du board sec." },
  { term: "Whale", def: "Un joueur très fortuné et faible, source de profit majeure. La « baleine » que tout le monde veut à sa table." },
  { term: "La roue", def: "La plus petite suite possible, A-2-3-4-5, où l'As compte comme un 1 (the wheel)." },
  { term: "HUD", def: "Head-Up Display : un logiciel qui affiche en temps réel les statistiques des adversaires sur les tables en ligne." },
  { term: "PFR", def: "Pre-Flop Raise : statistique mesurant la fréquence à laquelle un joueur relance avant le flop. Couplée au VPIP, elle décrit un style." },
  { term: "WTSD", def: "Went To Showdown : la fréquence à laquelle un joueur va jusqu'à l'abattage une fois le flop vu." },
  { term: "Fast-fold", def: "Format en ligne (Zoom, Rush) où l'on est instantanément placé à une nouvelle table dès qu'on se couche. Volume maximal." },
  { term: "Multi-tabling", def: "Jouer plusieurs tables en simultané, possible uniquement en ligne, pour augmenter le volume de mains." },
  { term: "Table selection", def: "Choisir ses tables en fonction des adversaires présents, pour s'asseoir là où l'on a le plus d'avantage." },
  { term: "Time bank", def: "Une réserve de temps supplémentaire, en ligne, qu'un joueur peut activer pour réfléchir sur une grosse décision." },
  { term: "Collusion", def: "Tricherie où plusieurs joueurs s'entendent secrètement contre les autres. Strictement interdite et sévèrement sanctionnée." },
  { term: "RTA", def: "Real-Time Assistance : utiliser un solver ou une aide pendant une partie en ligne. C'est de la triche, formellement interdite." },
  { term: "Bot", def: "Un programme automatisé qui joue à la place d'un humain. Interdit sur les salles en ligne, traqué en permanence." },
  { term: "Pression ICM", def: "La contrainte, en tournoi, de ne pas risquer son tournoi quand l'élimination coûte très cher en valeur (près de la bulle ou en table finale)." },
  { term: "Pay jump", def: "Le saut de gains entre deux places payées d'un tournoi. Plus il est gros, plus l'ICM pèse sur les décisions." },
  { term: "Ladder", def: "Grimper l'échelle des gains en tournoi en survivant aux éliminations, parfois sans jouer un seul coup." },
  { term: "Re-entry", def: "Format de tournoi qui autorise à se réinscrire après une élimination, pendant une période donnée." },
  { term: "Late registration", def: "La période d'inscription tardive d'un tournoi : on peut entrer après le début, souvent jusqu'à plusieurs niveaux." },
  { term: "Bagging", def: "Mettre ses jetons en sachet à la fin d'une journée de tournoi multi-day, pour les retrouver au redémarrage." },
  { term: "Big blind ante", def: "Une ante unique payée par la seule big blind pour toute la table, qui accélère le jeu et simplifie la donne." },
  { term: "SPR", def: "Stack-to-Pot Ratio : le rapport entre le tapis effectif et la taille du pot au flop. Il guide l'engagement (petit SPR = on s'engage facilement)." },
  { term: "Zone M", def: "Le M-ratio : le nombre de tours de table qu'un tapis peut tenir en payant les blindes et antes. Un faible M force le jeu push/fold." },
  { term: "Nash", def: "L'équilibre de Nash : en push/fold à tapis court, les ranges théoriquement inexploitables d'attaque et de défense." },
  { term: "Push/fold", def: "Le jeu à tapis court où l'on n'a plus que deux options préflop : faire tapis ou se coucher." },
  { term: "PKO", def: "Progressive Knockout : un tournoi à primes où éliminer un joueur rapporte une partie de sa prime, qui grossit votre propre tête." },
  { term: "Mystery bounty", def: "Format où chaque élimination débloque une prime au montant aléatoire, tirée au sort, parfois énorme." },
  { term: "Shot clock", def: "Un chronomètre qui limite le temps de réflexion de chaque joueur, de plus en plus courant en tournoi live." },
  { term: "Color up", def: "Échanger des piles de petits jetons contre des plus gros pour désencombrer la table, souvent avant un chip race." },
  { term: "Bad beat jackpot", def: "Un jackpot versé quand une très grosse main (souvent un carré ou mieux) est battue. Alimenté par un prélèvement dédié." },
  { term: "High hand", def: "Promotion qui récompense la plus belle main réalisée sur une période donnée dans une salle." },
  { term: "Nut low", def: "En Omaha hi-lo, la meilleure main basse possible, qui remporte la moitié basse du pot." },
  { term: "Big O", def: "Une variante d'Omaha jouée à cinq cartes en main au lieu de quatre, de plus en plus populaire." },
  { term: "Dangler", def: "En Omaha, une carte de votre main déconnectée des trois autres, qui ne sert presque jamais." },
  { term: "Cowboys", def: "Surnom de la paire de Rois (K-K). On dit aussi « cowboys » à cause des deux têtes." },
  { term: "Ducks", def: "Surnom de la paire de 2 (deux-deux), les « canards »." },
  { term: "Snowmen", def: "Surnom de la paire de 8 (huit-huit), les « bonshommes de neige »." },
  { term: "Fish hooks", def: "Surnom de la paire de Valets (J-J), les « hameçons »." },
  { term: "Rockets", def: "Surnom de la paire d'As (A-A), aussi appelée « pocket rockets » ou « bullets ». La meilleure main de départ." },
  { term: "Dead man's hand", def: "La « main du mort » : deux paires As et 8, que Wild Bill Hickok tenait, dit-on, quand il fut abattu." },
  { term: "Hammer", def: "Surnom du 7-2 dépareillé, la pire main de départ au Hold'em. Un « marteau » dont on est fier de gagner un coup." },
  { term: "Combinatoire", def: "Le décompte des combinaisons de cartes possibles dans la range d'un adversaire, pour estimer ce qu'il peut avoir." },
  { term: "Blocage", def: "Le fait de détenir une carte qui réduit le nombre de mains fortes possibles chez l'adversaire (removal). Voir aussi blocker." },
  { term: "Avantage de range", def: "Quand votre éventail de mains est globalement plus fort que celui de l'adversaire sur un tableau donné. Permet de miser plus souvent." },
  { term: "Range plafonnée", def: "Une range « cappée » qui ne contient aucune main très forte (par exemple parce qu'on aurait relancé avec). Une vraie faiblesse, exploitable." },
  { term: "Triple barrel", def: "Miser sur les trois tours (flop, turn, river), souvent en bluff prolongé. Voir barrel." },
  { term: "Bluff-catcher", def: "Une main moyenne qui ne bat que les bluffs : on la garde uniquement pour payer un adversaire qui pourrait bluffer." },
  { term: "Value fine", def: "Miser en valeur avec une main correcte mais pas énorme (thin value), en espérant être payé par moins bon." },
  { term: "Fusion de range", def: "Le « merging » : miser des mains moyennes en plus des fortes et des bluffs, pour rester difficile à lire." },
  { term: "Overfold", def: "Se coucher trop souvent face aux mises, plus que ce que la théorie recommande. C'est exploitable par le bluff." },
  { term: "Solver", def: "Un logiciel (comme PioSolver, GTO+) qui calcule la stratégie d'équilibre d'une situation. L'outil d'étude de référence." },
  { term: "Win rate", def: "Le taux de gain d'un joueur, mesuré en big blinds gagnées pour 100 mains (bb/100) en cash game." },
  { term: "Min-cash", def: "Atteindre tout juste la première place payée d'un tournoi, pour un gain minimal proche du buy-in." },
  { term: "Overlay", def: "Quand le prize pool garanti d'un tournoi dépasse la somme des buy-ins : la salle complète la différence. Une aubaine pour les joueurs." },
  { term: "Garanti", def: "Le montant minimum promis au prize pool d'un tournoi, quel que soit le nombre d'inscrits." },
  { term: "Carte brûlée", def: "La carte écartée face cachée par le croupier avant de dévoiler le flop, le turn et la river (la « burn card »)." },
  { term: "Carte de coupe", def: "La carte (souvent en plastique de couleur) placée sous le jeu pour masquer la carte du dessous (la « cut card »)." },
  { term: "Annonce verbale", def: "Au poker, une action annoncée à voix haute et à son tour est contraignante : dire « relance » vous engage à relancer." },
  { term: "Carte exposée", def: "Une carte involontairement montrée. Selon qui l'expose et quand, elle est remplacée, brûlée, ou reste au joueur." },
  { term: "Table stakes", def: "La règle qui veut qu'on ne joue qu'avec les jetons posés sur la table : on ne peut pas ajouter d'argent au milieu d'un coup." },
  { term: "Mixed games", def: "Les formats à rotation de variantes (HORSE, 8-game...), qui demandent de maîtriser plusieurs jeux." },
  { term: "Run good", def: "Traverser une bonne série, gagner plus que l'espérance le voudrait. L'inverse est le « run bad »." },
  { term: "Dead button", def: "Une règle de tournoi où le bouton se place sur un siège vide pour respecter l'ordre des blindes après une élimination." },
  { term: "Toke", def: "Le pourboire laissé au croupier par le gagnant d'un pot ou d'un tournoi. Une part importante du revenu d'un dealer." },
  { term: "Open-raise", def: "Être le premier à relancer préflop, en ouvrant l'action. Souvent abrégé « open »." },
  { term: "Limp-raise", def: "Limper puis relancer la mise d'un adversaire sur le même tour préflop. Un piège souvent synonyme de très grosse main." },
  { term: "Stab", def: "Tenter une mise quand l'adversaire montre de la faiblesse en checkant, même sans grande main." },
  { term: "Probe bet", def: "Miser en premier au turn, hors de position, après que le relanceur préflop a renoncé à c-bet le flop." },
  { term: "Donk (joueur)", def: "Diminutif de « donkey » : un joueur faible. À ne pas confondre avec le donk bet, qui est une mise." },
  { term: "Bomb pot", def: "Un coup spécial où tous les joueurs paient une mise forcée et où le flop est distribué directement, gonflant le pot d'entrée." },
  { term: "Sit & Go", def: "Un tournoi sur une seule table qui démarre dès qu'elle est pleine, sans horaire fixe. Souvent abrégé « SNG »." },
  { term: "Spin & Go", def: "Un Sit & Go à trois joueurs et à dotation tirée au sort, ultra rapide, avec parfois d'énormes multiplicateurs." },
  { term: "Spew", def: "Brûler des jetons par des mises agressives et mal fondées. « Il spew tout son tapis sur un bluff. »" },
  { term: "Soul read", def: "Une lecture quasi surnaturelle, deviner exactement la main de l'adversaire grâce à l'instinct et aux informations." },
  { term: "Snap", def: "Agir instantanément (snap call, snap fold) : la décision est tellement évidente qu'on ne réfléchit pas." },
  { term: "Double barrel", def: "Miser une deuxième fois, au turn, après avoir déjà c-bet le flop. La suite logique d'une pression entamée." },
  { term: "Delayed c-bet", def: "Renoncer à miser le flop pour finalement miser le turn. Un c-bet retardé, utile pour piéger ou contrôler le pot." },
  { term: "Check-call", def: "Checker puis payer la mise adverse. Une ligne passive qui garde le pot petit avec une main moyenne." },
  { term: "Check-fold", def: "Checker dans l'intention de se coucher si l'adversaire mise. On abandonne le coup à moindre coût." },
  { term: "Lead", def: "Mener la mise hors de position, en prenant l'initiative avant le relanceur préflop attendu. Voir aussi donk bet." },
  { term: "Backraise", def: "Limper ou suivre, puis relancer après la relance d'un autre joueur. Un piège qui simule la faiblesse." },
  { term: "Cold 4-bet", def: "4-better sans avoir encore investi dans le coup, en entrant directement sur un 3-bet adverse. Signal de très grande force, ou gros bluff." },
  { term: "Overlimp", def: "Limper derrière un ou plusieurs limpeurs, juste en complétant la grosse blinde, sans relancer." },
  { term: "Réalisation d'équité", def: "La capacité à transformer son équité théorique en gains réels. La position et l'initiative améliorent la réalisation d'équité." },
  { term: "Écart-type", def: "La mesure statistique de la dispersion des résultats. Plus il est élevé, plus la variance est forte." },
  { term: "Reg", def: "Un « regular » : un joueur régulier d'une limite ou d'un format, souvent solide et étudié. L'opposé du récréatif." },
  { term: "Récréatif", def: "Un joueur de loisir, qui joue pour le plaisir et non pour le profit. La cible commerciale des salles et le pain quotidien des regs." },
  { term: "TAG", def: "Tight-Aggressive : le style serré et agressif, considéré comme le plus rentable pour progresser. Peu de mains, mais jouées fort." },
  { term: "LAG", def: "Loose-Aggressive : un style large et agressif, qui met une pression constante. Redoutable mais exigeant et risqué." },
  { term: "Steam", def: "Une forme de tilt où la frustration monte coup après coup et dégrade les décisions sans qu'on s'en rende compte." },
  { term: "Monkey tilt", def: "La perte totale de contrôle émotionnel : on balance ses jetons n'importe comment. Le pire ennemi du joueur." },
  { term: "A-game", def: "Votre meilleur niveau de jeu, pleinement concentré et discipliné. L'objectif est d'y rester le plus longtemps possible." },
  { term: "Stop loss", def: "Une limite de pertes fixée à l'avance : on quitte la table une fois atteinte, pour éviter le tilt et les dégâts." },
  { term: "Shot taking", def: "Tenter sa chance à une limite supérieure avec une petite partie de sa bankroll, pour accélérer la progression." },
  { term: "Hand reading", def: "La lecture de main : reconstruire la range probable de l'adversaire en suivant ses actions tour après tour." },
  { term: "Metagame", def: "Le jeu autour du jeu : l'historique, les images et les ajustements mutuels entre joueurs qui se connaissent." },
  { term: "Table image", def: "La perception qu'ont les adversaires de votre façon de jouer. Une image serrée rend les bluffs plus crédibles." },
  { term: "Resteal", def: "Re-voler : 3-better un joueur qui tente de voler les blindes, souvent en bluff, pour récupérer le pot." },
  { term: "Open-fold", def: "Se coucher en premier de parole alors que personne n'est encore entré dans le coup. La décision la plus fréquente au poker." },
  { term: "Value town", def: "L'expression imagée pour dire qu'on a soutiré le maximum de valeur à un adversaire, mise après mise." },
  { term: "Equity denial", def: "Le déni d'équité : miser pour faire coucher une main qui aurait pu s'améliorer, et lui retirer ses chances de gagner." },
  { term: "Underbet", def: "Miser nettement moins que la taille du pot, pour des raisons précises (induire, miser fin, contrôler)." },
  { term: "Block bet", def: "Une petite mise de blocage, souvent à la river et hors de position, pour éviter de payer une plus grosse mise adverse." },
  { term: "Bet sizing", def: "Le dimensionnement des mises : choisir un montant cohérent avec son objectif (valeur, bluff, protection) et difficile à lire." },
  { term: "Way ahead, way behind", def: "Une situation où l'on est soit très largement devant, soit très largement derrière la range adverse, rarement entre les deux." },
  { term: "Underpair", def: "Une paire servie plus basse que la plus haute carte du tableau. Fragile, à l'inverse de l'overpair." },
  { term: "Middle pair", def: "Une paire formée avec la carte du milieu du tableau. Souvent juste un bluff-catcher." },
  { term: "Top set", def: "Le brelan le plus haut possible, formé avec une paire servie qui touche la plus haute carte du flop. Un monstre déguisé." },
  { term: "Combo draw", def: "Un tirage combiné, par exemple couleur plus quinte, qui offre énormément d'outs et souvent l'avantage à tapis." },
  { term: "Double belly buster", def: "Un tirage à deux ventres : deux quintes par le milieu en même temps, qui donne huit outs comme une quinte ouverte." },
  { term: "Second nuts", def: "La deuxième meilleure main possible. Très forte, mais à manier avec prudence face à une grosse agression." },
  { term: "Idiot end", def: "Le mauvais bout d'une suite : la suite la plus basse possible sur un tableau, qui peut être battue par une suite plus haute." },
  { term: "Wrap", def: "En Omaha, un tirage quinte enveloppant qui combine de nombreuses cartes et offre un nombre d'outs énorme." },
  { term: "Paired board", def: "Un tableau qui contient une paire. Il ouvre la possibilité d'un full ou d'un carré, et change la valeur des mains." },
  { term: "Monotone board", def: "Un flop de trois cartes de la même couleur. Très menaçant : la couleur est déjà possible." },
  { term: "Two-tone", def: "Un flop de deux cartes d'une couleur et une autre, qui permet un tirage couleur. Un board humide classique." },
  { term: "SRP", def: "Single-Raised Pot : un pot avec une seule relance préflop, sans 3-bet. La situation la plus fréquente." },
  { term: "Pot 3-bet", def: "Un pot où il y a eu une relance puis une sur-relance avant le flop. Les tapis sont plus engagés, les ranges plus serrées." },
  { term: "Main pot", def: "Le pot principal, par opposition au side pot, quand un ou plusieurs joueurs sont à tapis pour des montants différents." },
  { term: "Showdown value", def: "La valeur d'abattage : une main assez bonne pour gagner sans miser, simplement en allant à l'abattage." },
  { term: "Bubble factor", def: "Un coefficient qui mesure à quel point une élimination coûte cher en tournoi. Plus il est élevé, plus on joue serré." },
  { term: "Risk premium", def: "La prime de risque ICM : l'équité supplémentaire qu'il faut avoir pour justifier un tapis en tournoi, à cause du coût d'une élimination." },
  { term: "Nut advantage", def: "L'avantage des nuts : avoir, sur un tableau donné, plus de mains très fortes dans sa range que l'adversaire. Autorise les overbets." },
  { term: "Node locking", def: "Sur un solver, figer la stratégie de l'adversaire à une erreur précise pour voir comment l'exploiter au mieux." },
  { term: "Alpha", def: "En théorie des jeux, la fréquence de bluff qui rend l'adversaire indifférent entre payer et se coucher, liée à la taille de la mise." },
  { term: "Bink", def: "Toucher un gros coup ou remporter un tournoi de façon heureuse et inattendue. « Il a binké le satellite. »" },
  { term: "Punt", def: "Offrir bêtement ses jetons par une grosse erreur, souvent un bluff non réfléchi. Synonyme de « spew » version catastrophe." },
  { term: "Ship it", def: "L'exclamation du gagnant quand on lui pousse le pot : « envoie ! ». Aussi : faire tapis." },
  { term: "Stop and go", def: "En tournoi, suivre préflop hors de position pour faire tapis sur n'importe quel flop, et maximiser la fold equity." },
  { term: "Mississippi straddle", def: "Un straddle posé depuis une autre position que la première, là où c'est autorisé, qui rebat l'ordre de parole." },
  { term: "Kill pot", def: "Dans certaines parties, un pot joué à blindes doublées après qu'un joueur a remporté un ou plusieurs gros coups d'affilée." },
  { term: "Bring-in", def: "Au Stud, la mise forcée que doit poster le joueur montrant la plus petite carte, qui lance l'action." },
  { term: "Hollywooding", def: "Surjouer l'hésitation, faire du cinéma pour tromper l'adversaire sur la force de sa main. Mal vu si ça ralentit le jeu." },
  { term: "Linear range", def: "Une range linéaire : composée des meilleures mains de haut en bas, sans bluff, contrairement à une range polarisée." },
];
